/**
 * Kamus kode DP standar Tuya (Standard Instruction Set), dihasilkan dari dokumen
 * resmi developer.tuya.com untuk 35 kategori (diunduh & diurai 2026-10-03).
 * Dipakai untuk memberi nama ramah + arti pilihan pada perangkat APA PUN,
 * termasuk yang tidak dimiliki pengguna pertama (CCTV, robot vakum, kunci, sensor, dll).
 * Label kurasi di label-properti.ts tetap menang bila ada.
 * JANGAN sunting manual: bangun ulang dari kamus_dp_tuya.json.
 */

export type EntriDp = { id: string; en: string; ketId?: string; ketEn?: string; pilihan?: Record<string, { id: string; en: string }>; bacaSaja?: true };

export const KAMUS_DP: Record<string, EntriDp> = {
  "air_quality": {"id": "Kualitas udara", "en": "Air quality", "pilihan": {"great": {"id": "Sangat baik", "en": "Great"}, "mild": {"id": "Ringan", "en": "Mild"}, "good": {"id": "Baik", "en": "Good"}, "medium": {"id": "Sedang", "en": "Medium"}, "severe": {"id": "Parah", "en": "Severe"}}, "bacaSaja": true},
  "alarm_bright": {"id": "Kecerahan lampu alarm", "en": "Alarm light brightness"},
  "alarm_lock": {"id": "Peringatan kunci", "en": "Lock alert", "pilihan": {"wrong_finger": {"id": "Sidik jari salah", "en": "Wrong fingerprint"}, "wrong_password": {"id": "Sandi salah", "en": "Wrong password"}, "wrong_card": {"id": "Kartu salah", "en": "Wrong card"}, "wrong_face": {"id": "Wajah tidak cocok", "en": "Wrong face"}, "tongue_bad": {"id": "Lidah kunci rusak", "en": "Latch bolt fault"}, "too_hot": {"id": "Terlalu panas", "en": "Too hot"}, "tongue_not_out": {"id": "Lidah kunci tidak keluar", "en": "Latch bolt not out"}, "pry": {"id": "Dibongkar paksa", "en": "Pry alarm"}, "key_in": {"id": "Kunci mekanis dimasukkan", "en": "Key inserted"}, "power_off": {"id": "Daya mati", "en": "Power off"}, "shock": {"id": "Guncangan", "en": "Shock"}, "unclosed_time": {"id": "Pintu tidak ditutup", "en": "Door left open"}, "low_battery": {"id": "Baterai lemah", "en": "Low battery"}, "defense": {"id": "Alarm siaga", "en": "Armed alarm"}}, "bacaSaja": true},
  "alarm_ringtone": {"id": "Nada alarm", "en": "Alarm ringtone", "pilihan": {"1": {"id": "Nada 1", "en": "Tone 1"}, "2": {"id": "Nada 2", "en": "Tone 2"}, "3": {"id": "Nada 3", "en": "Tone 3"}, "4": {"id": "Nada 4", "en": "Tone 4"}, "5": {"id": "Nada 5", "en": "Tone 5"}}},
  "alarm_state": {"id": "Status alarm", "en": "Alarm status", "pilihan": {"alarm_sound": {"id": "Bunyi saja", "en": "Sound only"}, "alarm_light": {"id": "Lampu saja", "en": "Light only"}, "alarm_sound_light": {"id": "Bunyi + lampu", "en": "Sound + light"}, "normal": {"id": "Normal", "en": "Normal"}}},
  "alarm_switch": {"id": "Saklar alarm", "en": "Alarm switch"},
  "alarm_time": {"id": "Durasi alarm", "en": "Alarm duration"},
  "alarm_volume": {"id": "Volume alarm", "en": "Alarm volume", "pilihan": {"mute": {"id": "Senyap", "en": "Mute"}, "normal": {"id": "Normal", "en": "Normal"}, "loud": {"id": "Lantang", "en": "Loud"}, "low": {"id": "Pelan", "en": "Low"}, "middle": {"id": "Sedang", "en": "Medium"}, "high": {"id": "Keras", "en": "High"}}},
  "alert_state": {"id": "Siaga keamanan", "en": "Arm / disarm"},
  "anion": {"id": "Ion negatif", "en": "Anion", "ketId": "Pembangkit ion negatif.", "ketEn": "Negative ion generator."},
  "anti_lock_outside": {"id": "Kunci ganda angkat gagang", "en": "Double lock by lifting handle", "bacaSaja": true},
  "antilock_status": {"id": "Status kunci ganda", "en": "Double lock status", "pilihan": {"unknown": {"id": "Tidak diketahui", "en": "Unknown"}, "unlocked": {"id": "Tidak terkunci ganda", "en": "Not double-locked"}, "anti_locked": {"id": "Terkunci ganda", "en": "Double-locked"}}, "bacaSaja": true},
  "arming_switch": {"id": "Mode siaga", "en": "Arming"},
  "auto_lock_time": {"id": "Jeda kunci otomatis", "en": "Auto-lock delay"},
  "auto_power": {"id": "Mulai otomatis", "en": "Auto start"},
  "automatic_lock": {"id": "Kunci otomatis", "en": "Auto-lock"},
  "backlight": {"id": "Kecerahan layar", "en": "Backlight brightness"},
  "backlight_enum": {"id": "Lampu latar cepat", "en": "Backlight preset", "pilihan": {"closed": {"id": "Mati", "en": "Off"}, "half_bright": {"id": "Setengah terang", "en": "Half bright"}, "full_bright": {"id": "Terang penuh", "en": "Full bright"}}},
  "basic_anti_flicker": {"id": "Anti kedip", "en": "Anti-flicker", "pilihan": {"0": {"id": "Mati", "en": "Off"}, "1": {"id": "50 Hz", "en": "50 Hz"}, "2": {"id": "60 Hz", "en": "60 Hz"}}},
  "basic_device_volume": {"id": "Volume perangkat", "en": "Device volume"},
  "basic_flip": {"id": "Balik gambar", "en": "Flip image"},
  "basic_indicator": {"id": "Lampu indikator", "en": "Status light"},
  "basic_nightvision": {"id": "Penglihatan malam", "en": "Night vision", "pilihan": {"0": {"id": "Otomatis", "en": "Auto"}, "1": {"id": "Mati", "en": "Off"}, "2": {"id": "Nyala", "en": "On"}}},
  "basic_osd": {"id": "Tanda waktu di video", "en": "Time watermark"},
  "basic_private": {"id": "Mode privasi", "en": "Privacy mode", "ketId": "Kamera berhenti merekam/menampilkan gambar.", "ketEn": "Camera stops capturing/showing video."},
  "basic_shimmer": {"id": "Warna di cahaya redup", "en": "Low-light full color"},
  "basic_wdr": {"id": "Mode WDR", "en": "Wide dynamic range", "ketId": "Memperjelas gambar saat ada terang & gelap sekaligus.", "ketEn": "Improves images with strong light and shadow."},
  "battery": {"id": "Baterai (lama)", "en": "Battery (legacy)", "bacaSaja": true},
  "battery_percentage": {"id": "Baterai", "en": "Battery level", "bacaSaja": true},
  "battery_percentage_kit": {"id": "Baterai kamera", "en": "Camera battery status"},
  "battery_state": {"id": "Kondisi baterai", "en": "Battery status", "pilihan": {"high": {"id": "Penuh", "en": "High"}, "medium": {"id": "Sedang", "en": "Medium"}, "low": {"id": "Lemah", "en": "Low"}, "poweroff": {"id": "Habis", "en": "Power off"}, "middle": {"id": "Sedang", "en": "Medium"}, "mute": {"id": "Senyap", "en": "Mute"}}, "bacaSaja": true},
  "battery_value": {"id": "Nilai baterai", "en": "Battery value", "bacaSaja": true},
  "beep": {"id": "Bunyi beep", "en": "Beep"},
  "beep_volume": {"id": "Volume suara panduan", "en": "Voice guide volume", "pilihan": {"mute": {"id": "Senyap", "en": "Mute"}, "low": {"id": "Pelan", "en": "Low"}, "normal": {"id": "Normal", "en": "Normal"}, "high": {"id": "Keras", "en": "High"}}},
  "break_clean": {"id": "Lanjutkan pembersihan", "en": "Resume cleaning"},
  "bright_state": {"id": "Tingkat kecerahan", "en": "Brightness level", "pilihan": {"low": {"id": "Rendah", "en": "Low"}, "middle": {"id": "Sedang", "en": "Medium"}, "high": {"id": "Tinggi", "en": "High"}, "strong": {"id": "Sangat terang", "en": "Very bright"}}},
  "bright_value": {"id": "Kecerahan", "en": "Brightness"},
  "bright_value_1": {"id": "Kecerahan 1", "en": "Brightness 1"},
  "bright_value_2": {"id": "Kecerahan 2", "en": "Brightness 2"},
  "bright_value_3": {"id": "Kecerahan 3", "en": "Brightness 3"},
  "bright_value_v2": {"id": "Kecerahan", "en": "Brightness"},
  "brightness_max_1": {"id": "Kecerahan maks 1", "en": "Max brightness 1"},
  "brightness_max_2": {"id": "Kecerahan maks 2", "en": "Max brightness 2"},
  "brightness_max_3": {"id": "Kecerahan maks 3", "en": "Max brightness 3"},
  "brightness_min_1": {"id": "Kecerahan min 1", "en": "Min brightness 1"},
  "brightness_min_2": {"id": "Kecerahan min 2", "en": "Min brightness 2"},
  "brightness_min_3": {"id": "Kecerahan min 3", "en": "Min brightness 3"},
  "c_f": {"id": "Satuan suhu (lama)", "en": "Temperature unit (legacy)", "pilihan": {"C": {"id": "Celsius", "en": "Celsius"}, "F": {"id": "Fahrenheit", "en": "Fahrenheit"}}},
  "callphone": {"id": "Panggilan telepon", "en": "Phone call"},
  "capacity_expansion": {"id": "Tambah kapasitas", "en": "Capacity expansion"},
  "capacity_set": {"id": "Pengaturan daya", "en": "Power setting", "pilihan": {"2000W": {"id": "2000 W", "en": "2000 W"}, "3000W": {"id": "3000 W", "en": "3000 W"}, "5000W": {"id": "5000 W", "en": "5000 W"}, "2000w": {"id": "2000 W", "en": "2000 W"}, "3000w": {"id": "3000 W", "en": "3000 W"}, "5000w": {"id": "5000 W", "en": "5000 W"}}},
  "ch2o_value": {"id": "Kadar formaldehida", "en": "Formaldehyde level", "bacaSaja": true},
  "charge_state": {"id": "Sedang mengisi daya", "en": "Charging", "bacaSaja": true},
  "checking_result": {"id": "Hasil uji mandiri", "en": "Self-test result", "pilihan": {"checking": {"id": "Sedang diuji", "en": "Checking"}, "check_success": {"id": "Berhasil", "en": "Passed"}, "check_failure": {"id": "Gagal", "en": "Failed"}, "others": {"id": "Lainnya", "en": "Other"}}, "bacaSaja": true},
  "child_lock": {"id": "Kunci anak", "en": "Child lock"},
  "cistern": {"id": "Aliran air pel", "en": "Mop water flow", "pilihan": {"low": {"id": "Rendah", "en": "Low"}, "middle": {"id": "Sedang", "en": "Medium"}, "high": {"id": "Tinggi", "en": "High"}, "closed": {"id": "Mati", "en": "Off"}}},
  "clean_area": {"id": "Luas dibersihkan", "en": "Cleaned area", "bacaSaja": true},
  "clean_record": {"id": "Catatan bersih-bersih", "en": "Cleaning record", "bacaSaja": true},
  "clean_time": {"id": "Lama membersihkan", "en": "Cleaning time", "bacaSaja": true},
  "closed_opened": {"id": "Pintu terbuka/tertutup", "en": "Door open/closed", "pilihan": {"open": {"id": "Terbuka", "en": "Open"}, "closed": {"id": "Tertutup", "en": "Closed"}, "unknown": {"id": "Tidak diketahui", "en": "Unknown"}}, "bacaSaja": true},
  "closed_opened_kit": {"id": "Status pintu (akses)", "en": "Door status (access control)", "bacaSaja": true},
  "co2_state": {"id": "Status CO2", "en": "CO2 status", "pilihan": {"alarm": {"id": "Bahaya", "en": "Alarm"}, "normal": {"id": "Normal", "en": "Normal"}}, "bacaSaja": true},
  "co2_value": {"id": "Kadar CO2", "en": "CO2 level", "bacaSaja": true},
  "co_state": {"id": "Status CO", "en": "CO status", "pilihan": {"alarm": {"id": "Bahaya", "en": "Alarm"}, "normal": {"id": "Normal", "en": "Normal"}, "1": {"id": "Alarm", "en": "Alarm"}, "2": {"id": "Alarm berhenti", "en": "Alarm cleared"}}, "bacaSaja": true},
  "co_status": {"id": "Status CO", "en": "CO status", "pilihan": {"alarm": {"id": "Bahaya", "en": "Alarm"}, "normal": {"id": "Normal", "en": "Normal"}}, "bacaSaja": true},
  "co_value": {"id": "Kadar CO", "en": "CO level", "bacaSaja": true},
  "collection_mode": {"id": "Mode pengosongan debu", "en": "Dust collection mode", "pilihan": {"small": {"id": "Sedikit", "en": "Small"}, "middle": {"id": "Sedang", "en": "Medium"}, "large": {"id": "Banyak", "en": "Large"}}},
  "colour_data": {"id": "Warna lampu", "en": "Light color"},
  "colour_data_hsv": {"id": "Warna lampu (HSV)", "en": "Light color (HSV)"},
  "colour_data_v2": {"id": "Warna lampu", "en": "Light color"},
  "command_trans": {"id": "Kirim perintah", "en": "Command transmission"},
  "control": {"id": "Buka / tutup", "en": "Open / close", "pilihan": {"open": {"id": "Buka", "en": "Open"}, "stop": {"id": "Berhenti", "en": "Stop"}, "close": {"id": "Tutup", "en": "Close"}, "continue": {"id": "Lanjutkan", "en": "Continue"}}},
  "control_back": {"id": "Balik arah (lama)", "en": "Reverse (legacy)"},
  "control_back_mode": {"id": "Arah motor", "en": "Motor direction", "pilihan": {"forward": {"id": "Normal", "en": "Forward"}, "back": {"id": "Terbalik", "en": "Reverse"}}},
  "control_data": {"id": "Atur warna langsung", "en": "Direct light control"},
  "countdown": {"id": "Hitung mundur", "en": "Countdown", "pilihan": {"0": {"id": "Tingkat 0", "en": "Level 0"}, "1": {"id": "Tingkat 1", "en": "Level 1"}, "2": {"id": "Tingkat 2", "en": "Level 2"}, "3": {"id": "Tingkat 3", "en": "Level 3"}, "4": {"id": "Tingkat 4", "en": "Level 4"}, "5": {"id": "Tingkat 5", "en": "Level 5"}, "6": {"id": "Tingkat 6", "en": "Level 6"}, "cancel": {"id": "Batal", "en": "Cancel"}, "1h": {"id": "1 jam", "en": "1 h"}, "2h": {"id": "2 jam", "en": "2 h"}, "3h": {"id": "3 jam", "en": "3 h"}, "4h": {"id": "4 jam", "en": "4 h"}, "5h": {"id": "5 jam", "en": "5 h"}, "6h": {"id": "6 jam", "en": "6 h"}, "7h": {"id": "7 jam", "en": "7 h"}, "8h": {"id": "8 jam", "en": "8 h"}, "9h": {"id": "9 jam", "en": "9 h"}, "10h": {"id": "10 jam", "en": "10 h"}, "11h": {"id": "11 jam", "en": "11 h"}, "12h": {"id": "12 jam", "en": "12 h"}, "13h": {"id": "13 jam", "en": "13 h"}, "14h": {"id": "14 jam", "en": "14 h"}, "15h": {"id": "15 jam", "en": "15 h"}, "16h": {"id": "16 jam", "en": "16 h"}, "17h": {"id": "17 jam", "en": "17 h"}, "18h": {"id": "18 jam", "en": "18 h"}, "19h": {"id": "19 jam", "en": "19 h"}, "20h": {"id": "20 jam", "en": "20 h"}, "21h": {"id": "21 jam", "en": "21 h"}, "22h": {"id": "22 jam", "en": "22 h"}, "23h": {"id": "23 jam", "en": "23 h"}, "24h": {"id": "24 jam", "en": "24 h"}}},
  "countdown_1": {"id": "Timer saklar 1", "en": "Switch 1 timer", "ketId": "Detik sampai saklar berbalik.", "ketEn": "Seconds until the switch toggles."},
  "countdown_2": {"id": "Timer saklar 2", "en": "Switch 2 timer"},
  "countdown_3": {"id": "Timer saklar 3", "en": "Switch 3 timer"},
  "countdown_4": {"id": "Timer saklar 4", "en": "Switch 4 timer"},
  "countdown_5": {"id": "Timer saklar 5", "en": "Switch 5 timer"},
  "countdown_6": {"id": "Timer saklar 6", "en": "Switch 6 timer"},
  "countdown_alarm": {"id": "Tunda peringatan pintu", "en": "Door-open alert delay", "ketId": "Jika pintu garasi masih terbuka saat waktu habis, aplikasi kirim peringatan.", "ketEn": "If the garage door is still open when it ends, the app sends an alert."},
  "countdown_left": {"id": "Sisa hitung mundur", "en": "Countdown remaining", "bacaSaja": true},
  "countdown_set": {"id": "Hitung mundur", "en": "Countdown", "pilihan": {"cancel": {"id": "Batal", "en": "Cancel"}, "1h": {"id": "1 jam", "en": "1 h"}, "2h": {"id": "2 jam", "en": "2 h"}, "3h": {"id": "3 jam", "en": "3 h"}, "4h": {"id": "4 jam", "en": "4 h"}, "5h": {"id": "5 jam", "en": "5 h"}, "6h": {"id": "6 jam", "en": "6 h"}}},
  "countdown_usb1": {"id": "Timer USB 1", "en": "USB 1 timer"},
  "countdown_usb2": {"id": "Timer USB 2", "en": "USB 2 timer"},
  "countdown_usb3": {"id": "Timer USB 3", "en": "USB 3 timer"},
  "countdown_usb4": {"id": "Timer USB 4", "en": "USB 4 timer"},
  "countdown_usb5": {"id": "Timer USB 5", "en": "USB 5 timer"},
  "countdown_usb6": {"id": "Timer USB 6", "en": "USB 6 timer"},
  "cover_state": {"id": "Tutup wadah makanan", "en": "Food lid status", "pilihan": {"on": {"id": "Aktif", "en": "On"}, "off": {"id": "Tidak aktif", "en": "Off"}}, "bacaSaja": true},
  "cruise_mode": {"id": "Mode jelajah", "en": "Cruise mode", "pilihan": {"all_day": {"id": "Sepanjang hari", "en": "All day"}, "water_control": {"id": "Kendali air", "en": "Water control"}, "single_cruise": {"id": "Sekali jalan", "en": "Single cruise"}}},
  "cruise_switch": {"id": "Patroli otomatis", "en": "Cruise (patrol)"},
  "cry_detection_switch": {"id": "Deteksi tangisan", "en": "Cry detection"},
  "cur_current": {"id": "Arus listrik", "en": "Current", "bacaSaja": true},
  "cur_power": {"id": "Daya listrik", "en": "Power", "bacaSaja": true},
  "cur_voltage": {"id": "Tegangan", "en": "Voltage", "bacaSaja": true},
  "customize_mode_switch": {"id": "Mode kustom", "en": "Custom mode"},
  "cycle_time": {"id": "Siram berulang", "en": "Cycle irrigation"},
  "decibel_sensitivity": {"id": "Kepekaan suara", "en": "Sound sensitivity", "pilihan": {"0": {"id": "Rendah", "en": "Low"}, "1": {"id": "Tinggi", "en": "High"}}},
  "decibel_switch": {"id": "Deteksi suara", "en": "Sound detection"},
  "defrost": {"id": "Pencairan bunga es", "en": "Defrost"},
  "dehumidify_set_enum": {"id": "Target kelembapan", "en": "Target humidity", "pilihan": {"10": {"id": "10", "en": "10"}, "20": {"id": "20", "en": "20"}, "30": {"id": "30", "en": "30"}, "40": {"id": "40", "en": "40"}, "50": {"id": "50", "en": "50"}}},
  "dehumidify_set_value": {"id": "Target kelembapan", "en": "Target humidity"},
  "device_info": {"id": "Info perangkat", "en": "Device info"},
  "device_restart": {"id": "Mulai ulang perangkat", "en": "Restart device"},
  "device_timer": {"id": "Jadwal perangkat", "en": "Device timer"},
  "direction_control": {"id": "Arah gerak", "en": "Direction control", "pilihan": {"forward": {"id": "Maju", "en": "Forward"}, "backward": {"id": "Mundur", "en": "Backward"}, "turn_left": {"id": "Belok kiri", "en": "Turn left"}, "turn_right": {"id": "Belok kanan", "en": "Turn right"}, "stop": {"id": "Berhenti", "en": "Stop"}}},
  "disinfection": {"id": "Disinfeksi", "en": "Disinfection"},
  "disturb_time_set": {"id": "Jam jangan ganggu", "en": "DND schedule"},
  "do_not_disturb": {"id": "Jangan ganggu", "en": "Do not disturb"},
  "door_opened": {"id": "Pintu dibuka", "en": "Door opened", "bacaSaja": true},
  "door_unclosed_trigger": {"id": "Peringatan pintu terbuka", "en": "Door-open alert delay", "pilihan": {"5s": {"id": "5 detik", "en": "5 s"}, "10s": {"id": "10 detik", "en": "10 s"}, "15s": {"id": "15 detik", "en": "15 s"}, "20s": {"id": "20 detik", "en": "20 s"}, "25s": {"id": "25 detik", "en": "25 s"}}},
  "doorbell": {"id": "Bel ditekan", "en": "Doorbell pressed", "bacaSaja": true},
  "doorbell_song": {"id": "Nada bel", "en": "Doorbell tone", "pilihan": {"ding_0": {"id": "Nada 0", "en": "Tone 0"}, "ding_1": {"id": "Nada 1", "en": "Tone 1"}, "ding_2": {"id": "Nada 2", "en": "Tone 2"}, "ding_3": {"id": "Nada 3", "en": "Tone 3"}, "ding_4": {"id": "Nada 4", "en": "Tone 4"}, "ding_5": {"id": "Nada 5", "en": "Tone 5"}, "ding_6": {"id": "Nada 6", "en": "Tone 6"}, "ding_7": {"id": "Nada 7", "en": "Tone 7"}, "ding_8": {"id": "Nada 8", "en": "Tone 8"}, "ding_9": {"id": "Nada 9", "en": "Tone 9"}}},
  "doorbell_song_kit": {"id": "Panggilan bel", "en": "Doorbell call"},
  "doorbell_volume": {"id": "Volume bel", "en": "Doorbell volume", "pilihan": {"mute": {"id": "Senyap", "en": "Mute"}, "low": {"id": "Pelan", "en": "Low"}, "normal": {"id": "Normal", "en": "Normal"}, "high": {"id": "Keras", "en": "High"}}},
  "doorcontact_state": {"id": "Pintu/jendela terbuka", "en": "Door/window open", "bacaSaja": true},
  "dormant_switch": {"id": "Mode tidur", "en": "Hibernation"},
  "dormant_time_set": {"id": "Jadwal mode tidur", "en": "Hibernation schedule"},
  "dust_collection": {"id": "Kosongkan debu", "en": "Empty dustbin"},
  "dust_collection_num": {"id": "Frekuensi pengosongan", "en": "Dust emptying frequency"},
  "dust_collection_switch": {"id": "Stasiun pengosong debu", "en": "Dust collector"},
  "duster_cloth": {"id": "Umur kain pel", "en": "Mop cloth life", "bacaSaja": true},
  "eco": {"id": "Mode hemat", "en": "Eco mode"},
  "eco2": {"id": "Kadar eCO2", "en": "eCO2", "bacaSaja": true},
  "edge_brush": {"id": "Umur sikat samping", "en": "Side brush life", "bacaSaja": true},
  "edge_brush_life_reset": {"id": "Reset sikat samping", "en": "Reset side brush"},
  "electricity_left": {"id": "Sisa baterai", "en": "Battery left", "bacaSaja": true},
  "enforce_lock_up": {"id": "Wajib kunci ganda", "en": "Force double lock"},
  "export_calibrate": {"id": "Kalibrasi takaran", "en": "Calibrate portion"},
  "export_state": {"id": "Status kalibrasi takaran", "en": "Portion calibration status", "pilihan": {"true": {"id": "Ya", "en": "Yes"}, "false": {"id": "Tidak", "en": "No"}}, "bacaSaja": true},
  "factory_reset": {"id": "Reset pabrik", "en": "Factory reset"},
  "fan_beep": {"id": "Bunyi", "en": "Beep"},
  "fan_cool": {"id": "Angin sejuk", "en": "Cool breeze"},
  "fan_direction": {"id": "Arah putaran", "en": "Fan direction", "pilihan": {"forward": {"id": "Maju", "en": "Forward"}, "reverse": {"id": "Terbalik", "en": "Reverse"}}},
  "fan_horizontal": {"id": "Sudut ayun kiri-kanan", "en": "Horizontal swing angle", "pilihan": {"30": {"id": "30°", "en": "30°"}, "60": {"id": "60°", "en": "60°"}, "90": {"id": "90°", "en": "90°"}}},
  "fan_speed": {"id": "Kecepatan kipas (lama)", "en": "Fan speed (legacy)", "pilihan": {"1": {"id": "Tingkat 1", "en": "Level 1"}, "2": {"id": "Tingkat 2", "en": "Level 2"}, "3": {"id": "Tingkat 3", "en": "Level 3"}, "4": {"id": "Tingkat 4", "en": "Level 4"}}},
  "fan_speed_enum": {"id": "Kecepatan kipas", "en": "Fan speed", "pilihan": {"sleep": {"id": "Tidur", "en": "Sleep"}, "low": {"id": "Pelan", "en": "Low"}, "mid": {"id": "Sedang", "en": "Medium"}, "high": {"id": "Kencang", "en": "High"}, "auto": {"id": "Otomatis", "en": "Auto"}, "off": {"id": "Mati", "en": "Off"}, "strong": {"id": "Sangat kencang", "en": "Strong"}}},
  "fan_speed_percent": {"id": "Kecepatan kipas", "en": "Fan speed"},
  "fan_vertical": {"id": "Sudut ayun atas-bawah", "en": "Vertical swing angle", "pilihan": {"30": {"id": "30°", "en": "30°"}, "60": {"id": "60°", "en": "60°"}, "90": {"id": "90°", "en": "90°"}}},
  "fault": {"id": "Gangguan", "en": "Fault", "pilihan": {"sys_high_fault": {"id": "Gangguan sistem (tinggi)", "en": "System high fault"}, "sys_low_fault": {"id": "Gangguan sistem (rendah)", "en": "System low fault"}, "flow_fault": {"id": "Gangguan aliran air", "en": "Flow fault"}, "power_fault": {"id": "Gangguan daya", "en": "Power fault"}, "cooling_fault": {"id": "Gangguan pendinginan", "en": "Cooling fault"}, "heating_fault": {"id": "Gangguan pemanasan", "en": "Heating fault"}, "temp_dif_fault": {"id": "Gangguan selisih suhu", "en": "Temperature difference fault"}, "in_temp_fault": {"id": "Gangguan suhu masuk", "en": "Inlet temperature fault"}, "eff_temp_fault": {"id": "Gangguan suhu keluar", "en": "Effluent temperature fault"}, "coil_temp_fault": {"id": "Gangguan suhu koil", "en": "Coil temperature fault"}, "ret_temp_fault": {"id": "Gangguan suhu balik", "en": "Return temperature fault"}, "news_fault": {"id": "Gangguan \"news\"", "en": "News fault"}, "amb_temp_fault": {"id": "Gangguan suhu sekitar", "en": "Ambient temperature fault"}, "lack_water": {"id": "Kekurangan air", "en": "Lack of water"}, "serious_fault": {"id": "Gangguan serius", "en": "Serious fault"}, "sensor_fault": {"id": "Gangguan sensor", "en": "Sensor fault"}, "motor_fault": {"id": "Gangguan motor", "en": "Motor fault"}, "low_battery": {"id": "Baterai lemah", "en": "Low battery"}, "fault": {"id": "Gangguan", "en": "Fault"}}, "bacaSaja": true},
  "feed_report": {"id": "Hasil pemberian makan", "en": "Feeding result", "ketId": "Jumlah porsi yang keluar.", "ketEn": "Portions dispensed.", "bacaSaja": true},
  "feed_state": {"id": "Status pemberian makan", "en": "Feeding status", "pilihan": {"standby": {"id": "Siaga", "en": "Standby"}, "feeding": {"id": "Sedang memberi makan", "en": "Feeding"}, "done": {"id": "Selesai", "en": "Done"}}, "bacaSaja": true},
  "filter": {"id": "Umur filter", "en": "Filter life", "bacaSaja": true},
  "filter_days": {"id": "Sisa hari filter", "en": "Filter days left", "bacaSaja": true},
  "filter_reset": {"id": "Reset filter", "en": "Reset filter"},
  "flash_scene_1": {"id": "Adegan lembut", "en": "Soft light scene"},
  "flash_scene_2": {"id": "Adegan warna-warni", "en": "Colorful scene"},
  "flash_scene_3": {"id": "Adegan memukau", "en": "Dazzling scene"},
  "flash_scene_4": {"id": "Adegan megah", "en": "Gorgeous scene"},
  "flight_bright_mode": {"id": "Mode kecerahan", "en": "Brightness mode", "pilihan": {"0": {"id": "Manual", "en": "Manual"}, "1": {"id": "Otomatis", "en": "Auto"}}},
  "flight_pir_a": {"id": "Sensor gerak 1", "en": "PIR sensor 1"},
  "flight_pir_b": {"id": "Sensor gerak 2", "en": "PIR sensor 2"},
  "flight_pir_c": {"id": "Sensor gerak 3", "en": "PIR sensor 3"},
  "flight_warn_switch": {"id": "Saklar peringatan", "en": "Warning switch"},
  "floodlight_lightness": {"id": "Kecerahan lampu sorot", "en": "Floodlight brightness"},
  "floodlight_switch": {"id": "Lampu sorot", "en": "Floodlight"},
  "free_verify": {"id": "Buka tanpa verifikasi", "en": "Verification-free unlock"},
  "frost": {"id": "Anti beku", "en": "Anti-frost"},
  "gas_consumption": {"id": "Pemakaian gas", "en": "Gas consumption", "bacaSaja": true},
  "gas_sensor_state": {"id": "Status gas (lama)", "en": "Gas status (legacy)", "pilihan": {"1": {"id": "Alarm", "en": "Alarm"}, "2": {"id": "Alarm berhenti", "en": "Alarm cleared"}}, "bacaSaja": true},
  "gas_sensor_status": {"id": "Status gas", "en": "Gas status", "pilihan": {"alarm": {"id": "Bahaya", "en": "Alarm"}, "normal": {"id": "Normal", "en": "Normal"}}, "bacaSaja": true},
  "gas_sensor_value": {"id": "Kadar gas", "en": "Gas level", "bacaSaja": true},
  "heat": {"id": "Pemanas", "en": "Heating"},
  "heating_3d": {"id": "Pemanasan cepat 3D", "en": "3D fast heating"},
  "hijack": {"id": "Alarm paksaan", "en": "Duress alarm", "ketId": "Dibuka dengan sidik jari/sandi khusus saat dipaksa.", "ketEn": "Unlocked with a duress fingerprint/password.", "bacaSaja": true},
  "holiday_days_set": {"id": "Lama liburan", "en": "Holiday days"},
  "holiday_set": {"id": "Waktu liburan", "en": "Holiday time"},
  "holiday_temp_set": {"id": "Suhu mode liburan", "en": "Holiday temperature"},
  "holiday_temp_set_f": {"id": "Suhu liburan (°F)", "en": "Holiday temperature (°F)"},
  "hum_alarm": {"id": "Peringatan kelembapan", "en": "Humidity alert", "pilihan": {"loweralarm": {"id": "Terlalu rendah", "en": "Too low"}, "upperalarm": {"id": "Terlalu tinggi", "en": "Too high"}, "cancel": {"id": "Normal kembali", "en": "Cleared"}}, "bacaSaja": true},
  "hum_periodic_report": {"id": "Laporan kelembapan berkala", "en": "Humidity report interval"},
  "hum_sensitivity": {"id": "Kepekaan kelembapan", "en": "Humidity sensitivity"},
  "humidifier": {"id": "Pelembap", "en": "Humidifier"},
  "humidity": {"id": "Kelembapan", "en": "Humidity", "bacaSaja": true},
  "humidity_current": {"id": "Kelembapan saat ini", "en": "Current humidity", "bacaSaja": true},
  "humidity_indoor": {"id": "Kelembapan ruangan", "en": "Indoor humidity", "bacaSaja": true},
  "humidity_sampling": {"id": "Jeda baca kelembapan", "en": "Humidity sampling"},
  "humidity_set": {"id": "Target kelembapan", "en": "Target humidity"},
  "humidity_value": {"id": "Kelembapan", "en": "Humidity", "bacaSaja": true},
  "initiative_message": {"id": "Pesan notifikasi", "en": "Push messages"},
  "instant_heating": {"id": "Pemanasan instan", "en": "Instant heating"},
  "insurance_status": {"id": "Status pengaman", "en": "Latch status", "pilihan": {"unknown": {"id": "Tidak diketahui", "en": "Unknown"}, "uninsured_lock": {"id": "Pengaman tidak aktif", "en": "Not latched"}, "insured_lock": {"id": "Pengaman aktif", "en": "Latched"}}, "bacaSaja": true},
  "ipc_work_mode": {"id": "Mode kerja kamera", "en": "Camera work mode", "pilihan": {"0": {"id": "Hemat daya", "en": "Low power"}, "1": {"id": "Selalu menyala", "en": "Continuous"}}},
  "key_tone": {"id": "Volume tombol", "en": "Keypad volume", "pilihan": {"mute": {"id": "Senyap", "en": "Mute"}, "low": {"id": "Pelan", "en": "Low"}, "normal": {"id": "Normal", "en": "Normal"}, "high": {"id": "Keras", "en": "High"}}},
  "language": {"id": "Bahasa", "en": "Language", "pilihan": {"chinese_simplified": {"id": "Mandarin (sederhana)", "en": "Chinese (Simplified)"}, "chinese_traditional": {"id": "Mandarin (tradisional)", "en": "Chinese (Traditional)"}, "english": {"id": "Inggris", "en": "English"}, "german": {"id": "Jerman", "en": "German"}, "french": {"id": "Prancis", "en": "French"}, "russian": {"id": "Rusia", "en": "Russian"}, "spanish": {"id": "Spanyol", "en": "Spanish"}, "korean": {"id": "Korea", "en": "Korean"}, "latin": {"id": "Latin", "en": "Latin"}, "portuguese": {"id": "Portugis", "en": "Portuguese"}, "japanese": {"id": "Jepang", "en": "Japanese"}, "italian": {"id": "Italia", "en": "Italian"}}},
  "led_type_1": {"id": "Jenis lampu 1", "en": "Bulb type 1", "pilihan": {"led": {"id": "LED", "en": "LED"}, "incandescent": {"id": "Lampu pijar", "en": "Incandescent"}, "halogen": {"id": "Halogen", "en": "Halogen"}}},
  "led_type_2": {"id": "Jenis lampu 2", "en": "Bulb type 2", "pilihan": {"led": {"id": "LED", "en": "LED"}, "incandescent": {"id": "Lampu pijar", "en": "Incandescent"}, "halogen": {"id": "Halogen", "en": "Halogen"}}},
  "led_type_3": {"id": "Jenis lampu 3", "en": "Bulb type 3", "pilihan": {"led": {"id": "LED", "en": "LED"}, "incandescent": {"id": "Lampu pijar", "en": "Incandescent"}, "halogen": {"id": "Halogen", "en": "Halogen"}}},
  "level": {"id": "Tingkat", "en": "Level", "pilihan": {"1": {"id": "Tingkat 1", "en": "Level 1"}, "2": {"id": "Tingkat 2", "en": "Level 2"}, "3": {"id": "Tingkat 3", "en": "Level 3"}, "level_1": {"id": "Tingkat 1", "en": "Level 1"}, "level_2": {"id": "Tingkat 2", "en": "Level 2"}, "level_3": {"id": "Tingkat 3", "en": "Level 3"}, "level_4": {"id": "Tingkat 4", "en": "Level 4"}, "level_5": {"id": "Tingkat 5", "en": "Level 5"}, "level_6": {"id": "Tingkat 6", "en": "Level 6"}, "level_7": {"id": "Tingkat 7", "en": "Level 7"}, "level_8": {"id": "Tingkat 8", "en": "Level 8"}, "level_9": {"id": "Tingkat 9", "en": "Level 9"}, "level_10": {"id": "Tingkat 10", "en": "Level 10"}, "low": {"id": "Rendah", "en": "Low"}, "middle": {"id": "Sedang", "en": "Medium"}, "high": {"id": "Tinggi", "en": "High"}, "auto": {"id": "Otomatis", "en": "Auto"}, "closed": {"id": "Mati", "en": "Off"}}},
  "level_current": {"id": "Ketinggian air", "en": "Water level", "bacaSaja": true},
  "lifecycle": {"id": "Masa pakai sensor", "en": "Service life", "bacaSaja": true},
  "light": {"id": "Lampu", "en": "Light"},
  "light_mode": {"id": "Mode lampu indikator", "en": "Indicator light mode", "pilihan": {"none": {"id": "Selalu mati", "en": "Always off"}, "relay": {"id": "Ikut saklar", "en": "Follow switch"}, "pos": {"id": "Kebalikan saklar", "en": "Opposite of switch"}}},
  "lock": {"id": "Kunci anak", "en": "Child lock"},
  "lock_alarm_kit": {"id": "Riwayat peringatan", "en": "Alert history", "bacaSaja": true},
  "lock_function_switch": {"id": "Fungsi kunci", "en": "Lock function"},
  "lock_motor_direction": {"id": "Arah putar motor", "en": "Motor direction", "pilihan": {"clockwise": {"id": "Searah jarum jam", "en": "Clockwise"}, "anti_clockwise": {"id": "Berlawanan jarum jam", "en": "Anticlockwise"}}},
  "lock_motor_state": {"id": "Status kunci", "en": "Lock state", "ketId": "Status buka/tutup kunci.", "ketEn": "Lock open/closed status.", "bacaSaja": true},
  "lock_record": {"id": "Riwayat penguncian", "en": "Locking history", "bacaSaja": true},
  "loop_mode": {"id": "Mode sirkulasi", "en": "Loop mode", "pilihan": {"auto": {"id": "Otomatis", "en": "Auto"}, "indoor_loop": {"id": "Sirkulasi dalam", "en": "Indoor loop"}, "outdoor_loop": {"id": "Sirkulasi luar", "en": "Outdoor loop"}}},
  "low_power_threshold": {"id": "Batas baterai lemah", "en": "Low battery threshold", "pilihan": {"5_percent": {"id": "5%", "en": "5%"}, "10_percent": {"id": "10%", "en": "10%"}, "15_percent": {"id": "15%", "en": "15%"}, "20_percent": {"id": "20%", "en": "20%"}}},
  "lower_temp": {"id": "Suhu minimum", "en": "Min temperature"},
  "lower_temp_f": {"id": "Suhu minimum (°F)", "en": "Min temperature (°F)"},
  "mach_operate": {"id": "Gerak motor (lama)", "en": "Motor control (legacy)", "pilihan": {"ZZ": {"id": "Putar maju", "en": "Forward"}, "FZ": {"id": "Putar mundur", "en": "Reverse"}, "STOP": {"id": "Berhenti", "en": "Stop"}}},
  "manual_feed": {"id": "Beri makan manual", "en": "Manual feed", "ketId": "Jumlah porsi.", "ketEn": "Number of portions."},
  "master_mode": {"id": "Mode keamanan", "en": "Security mode", "pilihan": {"disarmed": {"id": "Nonaktif", "en": "Disarmed"}, "arm": {"id": "Siaga penuh", "en": "Armed"}, "home": {"id": "Di rumah", "en": "Home"}, "sos": {"id": "Darurat", "en": "SOS"}, "work": {"id": "Kerja", "en": "Work"}, "play": {"id": "Main", "en": "Play"}}},
  "maxhum_set": {"id": "Batas atas kelembapan", "en": "Max humidity limit"},
  "maxtemp_set": {"id": "Batas atas suhu", "en": "Max temperature limit"},
  "meal_plan": {"id": "Jadwal makan", "en": "Feeding schedule"},
  "minihum_set": {"id": "Batas bawah kelembapan", "en": "Min humidity limit"},
  "minitemp_set": {"id": "Batas bawah suhu", "en": "Min temperature limit"},
  "mode": {"id": "Mode", "en": "Mode", "pilihan": {"standby": {"id": "Siaga", "en": "Standby"}, "random": {"id": "Acak", "en": "Random"}, "smart": {"id": "Pintar / otomatis", "en": "Smart / auto"}, "wall_follow": {"id": "Sepanjang dinding", "en": "Along walls"}, "mop": {"id": "Mengepel", "en": "Mop"}, "spiral": {"id": "Spiral", "en": "Spiral"}, "left_spiral": {"id": "Spiral kiri", "en": "Left spiral"}, "right_spiral": {"id": "Spiral kanan", "en": "Right spiral"}, "right_bow": {"id": "Zig-zag kanan", "en": "Right bow"}, "left_bow": {"id": "Zig-zag kiri", "en": "Left bow"}, "partial_bow": {"id": "Zig-zag sebagian", "en": "Partial bow"}, "chargego": {"id": "Kembali mengisi daya", "en": "Return to charge"}, "bow": {"id": "Zig-zag", "en": "Bow (zigzag)"}, "single": {"id": "Tunggal", "en": "Single"}, "zone": {"id": "Zona", "en": "Zone"}, "pose": {"id": "Ke posisi", "en": "Pose"}, "point": {"id": "Titik", "en": "Point"}, "part": {"id": "Sebagian", "en": "Part"}, "pick_zone": {"id": "Zona pilihan", "en": "Picked zone"}, "nature": {"id": "Angin alami", "en": "Natural wind"}, "sleep": {"id": "Tidur", "en": "Sleep"}, "fresh": {"id": "Segar", "en": "Fresh"}, "auto": {"id": "Otomatis", "en": "Auto"}, "manual": {"id": "Manual", "en": "Manual"}, "pollen": {"id": "Serbuk sari", "en": "Pollen"}, "comfortable": {"id": "Nyaman", "en": "Comfort"}, "strong": {"id": "Kuat", "en": "Strong"}, "large": {"id": "Kabut banyak", "en": "Large mist"}, "middle": {"id": "Sedang", "en": "Medium"}, "small": {"id": "Kabut sedikit", "en": "Small mist"}, "interval": {"id": "Berselang", "en": "Interval"}, "continuous": {"id": "Terus-menerus", "en": "Continuous"}, "dehumidify": {"id": "Kurangi lembap", "en": "Dehumidify"}, "drying": {"id": "Pengeringan", "en": "Drying"}, "cold": {"id": "Dingin", "en": "Cool"}, "hot": {"id": "Panas", "en": "Heat"}, "wind": {"id": "Kipas", "en": "Fan"}, "energy": {"id": "Hemat energi", "en": "Energy saving"}, "holiday": {"id": "Liburan", "en": "Holiday"}, "eco": {"id": "Hemat", "en": "Eco"}, "dry": {"id": "Kering", "en": "Dry"}, "program": {"id": "Terjadwal", "en": "Program"}, "floor_heat": {"id": "Pemanas lantai", "en": "Floor heating"}, "auxiliary_heat": {"id": "Pemanas tambahan", "en": "Auxiliary heat"}, "morning": {"id": "Pagi", "en": "Morning"}, "night": {"id": "Malam", "en": "Night"}, "wet": {"id": "Pengurang lembap", "en": "Dehumidify (wet)"}, "floor_heat_and_heat": {"id": "Pemanas lantai + panas", "en": "Floor heat + heat"}, "low": {"id": "Rendah", "en": "Low"}, "high": {"id": "Tinggi", "en": "High"}, "antifreeze": {"id": "Anti beku", "en": "Antifreeze"}, "adaptive": {"id": "Adaptif", "en": "Adaptive"}, "kitchen": {"id": "Dapur", "en": "Kitchen"}, "bathtub": {"id": "Bak mandi", "en": "Bathtub"}, "water_full": {"id": "Air penuh", "en": "Full water"}, "wash": {"id": "Cuci", "en": "Wash"}, "laundry": {"id": "Cuci pakaian", "en": "Laundry"}, "spring": {"id": "Musim semi", "en": "Spring"}, "summer": {"id": "Musim panas", "en": "Summer"}, "autumn": {"id": "Musim gugur", "en": "Autumn"}, "winter": {"id": "Musim dingin", "en": "Winter"}}},
  "mode_auto": {"id": "Mode otomatis", "en": "Auto mode"},
  "mode_dry": {"id": "Mode kering", "en": "Dry mode"},
  "mode_eco": {"id": "Mode hemat", "en": "Eco mode"},
  "mode_ventilation": {"id": "Mode ventilasi", "en": "Ventilation mode"},
  "moodlighting": {"id": "Lampu suasana (lama)", "en": "Mood light (legacy)", "pilihan": {"1": {"id": "Pilihan 1", "en": "Option 1"}, "2": {"id": "Pilihan 2", "en": "Option 2"}, "3": {"id": "Pilihan 3", "en": "Option 3"}, "4": {"id": "Pilihan 4", "en": "Option 4"}, "5": {"id": "Pilihan 5", "en": "Option 5"}}},
  "motion_interval": {"id": "Jeda peringatan", "en": "Alert interval", "pilihan": {"1": {"id": "1 menit", "en": "1 min"}, "3": {"id": "3 menit", "en": "3 min"}, "5": {"id": "5 menit", "en": "5 min"}}},
  "motion_record": {"id": "Mode rekam kartu SD", "en": "SD recording mode"},
  "motion_sensitivity": {"id": "Kepekaan gerakan", "en": "Motion sensitivity", "pilihan": {"0": {"id": "Rendah", "en": "Low"}, "1": {"id": "Sedang", "en": "Medium"}, "2": {"id": "Tinggi", "en": "High"}}},
  "motion_switch": {"id": "Deteksi gerakan", "en": "Motion detection"},
  "motion_timer_switch": {"id": "Mode deteksi gerakan", "en": "Motion detection mode"},
  "motion_tracking": {"id": "Ikuti gerakan", "en": "Motion tracking"},
  "motor_torque": {"id": "Tenaga motor", "en": "Motor torque", "pilihan": {"torque_low": {"id": "Rendah", "en": "Low"}, "torque_middle": {"id": "Sedang", "en": "Medium"}, "torque_high": {"id": "Tinggi", "en": "High"}}},
  "muffling": {"id": "Bisukan alarm", "en": "Mute alarm"},
  "music_data": {"id": "Lampu ikut musik", "en": "Music light"},
  "mute_mode_period": {"id": "Jam senyap", "en": "Mute schedule"},
  "night_power": {"id": "Daya malam hari", "en": "Night power"},
  "no_irrigation_time": {"id": "Waktu larangan siram", "en": "No-irrigation period"},
  "normal_open_period": {"id": "Jadwal selalu terbuka", "en": "Always-open schedule"},
  "normal_open_switch": {"id": "Mode selalu terbuka", "en": "Always-open mode"},
  "normal_timer": {"id": "Jadwal siram", "en": "Irrigation schedule"},
  "open_close": {"id": "Kunci dibuka/dikunci", "en": "Lock/unlock event", "bacaSaja": true},
  "open_inside": {"id": "Dibuka dari dalam", "en": "Opened from inside", "bacaSaja": true},
  "open_rate": {"id": "Persentase bukaan", "en": "Opening percentage"},
  "open_speed_state": {"id": "Kecepatan buka", "en": "Unlock speed", "pilihan": {"low": {"id": "Rendah", "en": "Low"}, "middle": {"id": "Sedang", "en": "Medium"}, "high": {"id": "Tinggi", "en": "High"}}},
  "opposite": {"id": "Balik arah (lama)", "en": "Reverse direction (legacy)"},
  "outage": {"id": "Air mati", "en": "Water outage"},
  "oxygen": {"id": "Oksigen", "en": "Oxygen bar"},
  "path_data": {"id": "Data jalur", "en": "Path data"},
  "pause": {"id": "Jeda", "en": "Pause"},
  "percent_control": {"id": "Atur bukaan", "en": "Set opening"},
  "percent_state": {"id": "Bukaan saat ini", "en": "Current opening", "bacaSaja": true},
  "photo_mode": {"id": "Mode foto", "en": "Photo mode", "pilihan": {"close": {"id": "Mati", "en": "Off"}, "power_save": {"id": "Hemat daya", "en": "Power saving"}, "standard": {"id": "Standar", "en": "Standard"}, "security": {"id": "Keamanan", "en": "Security"}}},
  "pir": {"id": "Gerakan terdeteksi", "en": "Motion detected", "pilihan": {"pir": {"id": "Ada gerakan", "en": "Motion"}, "none": {"id": "Tidak ada gerakan", "en": "No motion"}}, "bacaSaja": true},
  "pir_sensitivity": {"id": "Kepekaan sensor gerak", "en": "PIR sensitivity", "pilihan": {"0": {"id": "Rendah", "en": "Low"}, "1": {"id": "Sedang", "en": "Medium"}, "2": {"id": "Tinggi", "en": "High"}}},
  "pm1": {"id": "PM1.0", "en": "PM1.0", "bacaSaja": true},
  "pm10": {"id": "PM10", "en": "PM10", "bacaSaja": true},
  "pm25": {"id": "PM2.5", "en": "PM2.5", "bacaSaja": true},
  "pm25_state": {"id": "Status PM2.5", "en": "PM2.5 status", "pilihan": {"alarm": {"id": "Bahaya", "en": "Alarm"}, "normal": {"id": "Normal", "en": "Normal"}}, "bacaSaja": true},
  "pm25_value": {"id": "Kadar PM2.5", "en": "PM2.5 level", "bacaSaja": true},
  "position": {"id": "Posisi tirai (lama)", "en": "Curtain position (legacy)"},
  "power": {"id": "Nyala / mati", "en": "Power"},
  "power_consumption": {"id": "Pemakaian listrik", "en": "Power consumption", "bacaSaja": true},
  "power_go": {"id": "Mulai bersih-bersih", "en": "Start cleaning"},
  "preheat": {"id": "Pemanasan sensor", "en": "Sensor warming up", "ketId": "Sensor sedang pemanasan, hasil belum akurat.", "ketEn": "Sensor is warming up; readings not yet accurate.", "bacaSaja": true},
  "ptz_calibration": {"id": "Kalibrasi arah kamera", "en": "PTZ calibration"},
  "ptz_control": {"id": "Arah gerak kamera", "en": "Pan/tilt direction", "pilihan": {"0": {"id": "Atas", "en": "Up"}, "1": {"id": "Kanan atas", "en": "Upper right"}, "2": {"id": "Kanan", "en": "Right"}, "3": {"id": "Kanan bawah", "en": "Lower right"}, "4": {"id": "Bawah", "en": "Down"}, "5": {"id": "Kiri bawah", "en": "Lower left"}, "6": {"id": "Kiri", "en": "Left"}, "7": {"id": "Kiri atas", "en": "Upper left"}}},
  "ptz_stop": {"id": "Hentikan gerak kamera", "en": "Stop pan/tilt"},
  "quick_feed": {"id": "Beri makan cepat", "en": "Quick feed"},
  "rag_life_reset": {"id": "Reset kain pel", "en": "Reset mop cloth"},
  "read_time": {"id": "Waktu baca", "en": "Reading time"},
  "record_mode": {"id": "Mode rekam", "en": "Recording mode", "pilihan": {"1": {"id": "Saat ada kejadian", "en": "Event recording"}, "2": {"id": "Terus-menerus", "en": "Continuous"}}},
  "record_switch": {"id": "Rekam ke kartu SD", "en": "SD card recording"},
  "relay_status": {"id": "Saat listrik kembali", "en": "Power-on behavior", "pilihan": {"power_on": {"id": "Menyala", "en": "On"}, "power_off": {"id": "Mati", "en": "Off"}, "last": {"id": "Seperti terakhir", "en": "Last state"}, "off": {"id": "Mati", "en": "Off"}, "on": {"id": "Menyala", "en": "On"}, "memory": {"id": "Seperti terakhir", "en": "Last state"}}},
  "remote_result": {"id": "Hasil buka jarak jauh", "en": "Remote unlock result"},
  "request": {"id": "Minta data", "en": "Request data", "pilihan": {"get_map": {"id": "Ambil peta", "en": "Get map"}, "get_path": {"id": "Ambil jalur", "en": "Get path"}, "get_both": {"id": "Ambil peta & jalur", "en": "Get map & path"}}},
  "reset_duster_cloth": {"id": "Reset kain pel", "en": "Reset mop cloth"},
  "reset_edge_brush": {"id": "Reset sikat samping", "en": "Reset side brush"},
  "reset_filter": {"id": "Reset filter", "en": "Reset filter"},
  "reset_map": {"id": "Reset peta", "en": "Reset map"},
  "reset_roll_brush": {"id": "Reset sikat utama", "en": "Reset main brush"},
  "residual_electricity": {"id": "Sisa baterai", "en": "Battery left", "bacaSaja": true},
  "rest_time": {"id": "Waktu istirahat", "en": "Rest time"},
  "reverse_lock": {"id": "Kunci ganda", "en": "Double locked", "bacaSaja": true},
  "rhythm_mode": {"id": "Ritme harian", "en": "Circadian rhythm"},
  "ringtone": {"id": "Nada dering", "en": "Ringtone", "pilihan": {"sound_1": {"id": "Nada 1", "en": "Tone 1"}, "sound_2": {"id": "Nada 2", "en": "Tone 2"}, "sound_3": {"id": "Nada 3", "en": "Tone 3"}, "sound_4": {"id": "Nada 4", "en": "Tone 4"}, "sound_5": {"id": "Nada 5", "en": "Tone 5"}, "sound_6": {"id": "Nada 6", "en": "Tone 6"}}},
  "roll_brush": {"id": "Umur sikat utama", "en": "Main brush life", "bacaSaja": true},
  "sampling_humidity": {"id": "Jeda baca kelembapan", "en": "Humidity sampling interval"},
  "sampling_temperature": {"id": "Jeda baca suhu", "en": "Temperature sampling interval"},
  "scene_1": {"id": "Adegan 1", "en": "Scene 1", "ketId": "Tombol pemicu adegan.", "ketEn": "Scene trigger button.", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_10": {"id": "Adegan 10", "en": "Scene 10", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_11": {"id": "Adegan 11", "en": "Scene 11", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_12": {"id": "Adegan 12", "en": "Scene 12", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_13": {"id": "Adegan 13", "en": "Scene 13", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_14": {"id": "Adegan 14", "en": "Scene 14", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_15": {"id": "Adegan 15", "en": "Scene 15", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_16": {"id": "Adegan 16", "en": "Scene 16", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_2": {"id": "Adegan 2", "en": "Scene 2", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_3": {"id": "Adegan 3", "en": "Scene 3", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_4": {"id": "Adegan 4", "en": "Scene 4", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_5": {"id": "Adegan 5", "en": "Scene 5", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_6": {"id": "Adegan 6", "en": "Scene 6", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_7": {"id": "Adegan 7", "en": "Scene 7", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_8": {"id": "Adegan 8", "en": "Scene 8", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_9": {"id": "Adegan 9", "en": "Scene 9", "pilihan": {"scene": {"id": "Jalankan adegan", "en": "Run scene"}}},
  "scene_data": {"id": "Adegan lampu", "en": "Light scene"},
  "scene_data_v2": {"id": "Adegan lampu", "en": "Light scene"},
  "scene_id_group_id": {"id": "ID adegan & grup", "en": "Scene & group ID"},
  "scene_select": {"id": "Pilih adegan", "en": "Scene selection", "pilihan": {"1": {"id": "Membaca", "en": "Reading"}, "2": {"id": "Kerja komputer", "en": "Computer"}, "3": {"id": "Lampu tidur", "en": "Night light"}, "4": {"id": "Santai", "en": "Leisure"}, "5": {"id": "Redup", "en": "Dim"}}},
  "sd_format": {"id": "Format kartu SD", "en": "Format SD card"},
  "sd_format_state": {"id": "Progres format SD", "en": "SD format progress", "bacaSaja": true},
  "sd_status": {"id": "Status kartu SD", "en": "SD card status", "pilihan": {"1": {"id": "Normal", "en": "Normal"}, "2": {"id": "Bermasalah", "en": "Error"}, "3": {"id": "Penuh", "en": "Not enough space"}, "4": {"id": "Sedang diformat", "en": "Formatting"}, "5": {"id": "Tidak ada kartu", "en": "No SD card"}}, "bacaSaja": true},
  "sd_storge": {"id": "Kapasitas kartu SD", "en": "SD card capacity", "bacaSaja": true},
  "sd_umount": {"id": "Lepas kartu SD", "en": "Unmount SD card"},
  "seek": {"id": "Cari robot", "en": "Find robot"},
  "self_checking": {"id": "Uji mandiri", "en": "Self-test"},
  "sensor_choose": {"id": "Pilihan sensor", "en": "Sensor selection", "pilihan": {"in": {"id": "Sensor dalam", "en": "Internal sensor"}, "out": {"id": "Sensor luar", "en": "External sensor"}}},
  "sensor_humidity": {"id": "Kelembapan", "en": "Humidity", "bacaSaja": true},
  "sensor_temperature": {"id": "Suhu", "en": "Temperature", "bacaSaja": true},
  "shake": {"id": "Ayun", "en": "Oscillation"},
  "signal_strength": {"id": "Kekuatan sinyal", "en": "Signal strength", "bacaSaja": true},
  "siren_switch": {"id": "Sirene", "en": "Siren"},
  "situation_set": {"id": "Posisi akhir", "en": "End position", "pilihan": {"fully_open": {"id": "Terbuka penuh", "en": "Fully open"}, "fully_close": {"id": "Tertutup penuh", "en": "Fully closed"}}, "bacaSaja": true},
  "sleep": {"id": "Mode tidur", "en": "Sleep mode"},
  "sleep_mode": {"id": "Mode tidur lampu", "en": "Sleep (lighting)"},
  "slow_feed": {"id": "Beri makan perlahan", "en": "Slow feed"},
  "smart_change": {"id": "Ganti pintar", "en": "Smart change"},
  "smart_weather": {"id": "Cuaca", "en": "Weather", "pilihan": {"sunny": {"id": "Cerah", "en": "Sunny"}, "clear": {"id": "Langit bersih", "en": "Clear"}, "cloud": {"id": "Berawan", "en": "Cloud"}, "cloudy": {"id": "Mendung", "en": "Cloudy"}, "rainy": {"id": "Hujan", "en": "Rainy"}, "snow": {"id": "Salju", "en": "Snow"}, "fog": {"id": "Kabut", "en": "Fog"}}},
  "smoke_sensor_state": {"id": "Status asap (lama)", "en": "Smoke status (legacy)", "pilihan": {"1": {"id": "Alarm", "en": "Alarm"}, "2": {"id": "Alarm berhenti", "en": "Alarm cleared"}}, "bacaSaja": true},
  "smoke_sensor_status": {"id": "Status asap", "en": "Smoke status", "pilihan": {"alarm": {"id": "Bahaya", "en": "Alarm"}, "normal": {"id": "Normal", "en": "Normal"}}, "bacaSaja": true},
  "smoke_sensor_value": {"id": "Kadar asap", "en": "Smoke level", "bacaSaja": true},
  "sound": {"id": "Suara", "en": "Sound"},
  "sound_mode": {"id": "Mode suara", "en": "Sound mode", "pilihan": {"ringtone_0": {"id": "Nada 0", "en": "Tone 0"}, "ringtone_1": {"id": "Nada 1", "en": "Tone 1"}, "ringtone_2": {"id": "Nada 2", "en": "Tone 2"}, "ringtone_3": {"id": "Nada 3", "en": "Tone 3"}, "ringtone_4": {"id": "Nada 4", "en": "Tone 4"}, "ringtone_5": {"id": "Nada 5", "en": "Tone 5"}}},
  "special_control": {"id": "Kontrol khusus", "en": "Special control"},
  "special_function": {"id": "Fungsi khusus", "en": "Special function", "pilihan": {"function1": {"id": "Fungsi 1", "en": "Function 1"}, "function2": {"id": "Fungsi 2", "en": "Function 2"}, "function3": {"id": "Fungsi 3", "en": "Function 3"}, "function4": {"id": "Fungsi 4", "en": "Function 4"}, "function5": {"id": "Fungsi 5", "en": "Function 5"}, "function6": {"id": "Fungsi 6", "en": "Function 6"}}},
  "speed": {"id": "Tingkat kecepatan", "en": "Speed level", "pilihan": {"1": {"id": "Tingkat 1", "en": "Level 1"}, "2": {"id": "Tingkat 2", "en": "Level 2"}, "3": {"id": "Tingkat 3", "en": "Level 3"}, "4": {"id": "Tingkat 4", "en": "Level 4"}, "5": {"id": "Tingkat 5", "en": "Level 5"}, "6": {"id": "Tingkat 6", "en": "Level 6"}}},
  "spray_mode": {"id": "Mode semprot", "en": "Spray mode", "pilihan": {"auto": {"id": "Otomatis", "en": "Auto"}, "health": {"id": "Sehat", "en": "Health"}, "baby": {"id": "Bayi", "en": "Baby"}, "sleep": {"id": "Tidur", "en": "Sleep"}, "humidity": {"id": "Jaga kelembapan", "en": "Humidity"}, "work": {"id": "Kerja", "en": "Work"}}},
  "start": {"id": "Mulai", "en": "Start"},
  "status": {"id": "Status", "en": "Status", "pilihan": {"standby": {"id": "Siaga", "en": "Standby"}, "smart_clean": {"id": "Bersih otomatis", "en": "Auto cleaning"}, "wall_clean": {"id": "Bersih tepi", "en": "Edge cleaning"}, "spot_clean": {"id": "Bersih titik", "en": "Spot cleaning"}, "mop_clean": {"id": "Mengepel", "en": "Mopping"}, "goto_charge": {"id": "Kembali ke dok", "en": "Returning to dock"}, "charging": {"id": "Mengisi daya", "en": "Charging"}, "charge_done": {"id": "Baterai penuh", "en": "Charged"}, "paused": {"id": "Dijeda", "en": "Paused"}, "cleaning": {"id": "Membersihkan", "en": "Cleaning"}, "zone_clean": {"id": "Bersih zona", "en": "Zone cleaning"}, "part_clean": {"id": "Bersih sebagian", "en": "Part cleaning"}, "pick_zone_clean": {"id": "Bersih zona pilihan", "en": "Picked-zone cleaning"}, "goto_pos": {"id": "Menuju titik", "en": "Going to point"}, "pos_arrived": {"id": "Tiba di titik", "en": "Arrived at point"}, "pos_unarrive": {"id": "Gagal ke titik", "en": "Point not reached"}, "sleep": {"id": "Tidur", "en": "Sleeping"}, "heating": {"id": "Memanaskan", "en": "Heating"}, "cooling": {"id": "Mendinginkan", "en": "Cooling"}, "warm": {"id": "Jaga hangat", "en": "Keeping warm"}, "heating_temp": {"id": "Memanaskan ke suhu", "en": "Heating to temp"}, "boiling_temp": {"id": "Didihkan lalu ke suhu", "en": "Boil then to temp"}, "reserve_1": {"id": "Cadangan 1", "en": "Reserved 1"}, "reserve_2": {"id": "Cadangan 2", "en": "Reserved 2"}, "reserve_3": {"id": "Cadangan 3", "en": "Reserved 3"}, "1": {"id": "1", "en": "1"}, "2": {"id": "2", "en": "2"}, "3": {"id": "3", "en": "3"}, "off": {"id": "Mati", "en": "Off"}}, "bacaSaja": true},
  "stay_alarm_mode": {"id": "Peringatan mondar-mandir", "en": "Loitering alert", "pilihan": {"close": {"id": "Mati", "en": "Off"}, "normal": {"id": "Normal", "en": "Normal"}, "high": {"id": "Tinggi", "en": "High"}, "custom": {"id": "Kustom", "en": "Custom"}}},
  "stay_capture_mode": {"id": "Mode foto mondar-mandir", "en": "Loitering capture mode", "pilihan": {"mode_1": {"id": "Mode 1", "en": "Mode 1"}, "mode_2": {"id": "Mode 2", "en": "Mode 2"}}},
  "stay_hold_time": {"id": "Durasi deteksi mondar-mandir", "en": "Loitering hold time"},
  "stay_trigger_distance": {"id": "Jarak deteksi mondar-mandir", "en": "Loitering range", "pilihan": {"away_from": {"id": "Jauh", "en": "Far"}, "close_to": {"id": "Dekat", "en": "Near"}, "middle": {"id": "Sedang", "en": "Medium"}}},
  "sterilization": {"id": "Sterilisasi", "en": "Sterilization"},
  "suction": {"id": "Daya hisap", "en": "Suction power", "pilihan": {"strong": {"id": "Kuat", "en": "Strong"}, "normal": {"id": "Normal", "en": "Normal"}, "quiet": {"id": "Senyap", "en": "Quiet"}, "gentle": {"id": "Lembut", "en": "Gentle"}, "closed": {"id": "Mati", "en": "Off"}}},
  "surplus_grain": {"id": "Sisa makanan", "en": "Food left", "bacaSaja": true},
  "surplus_water": {"id": "Sisa air", "en": "Water left", "bacaSaja": true},
  "swing": {"id": "Ayun", "en": "Swing"},
  "switch": {"id": "Nyala / mati", "en": "Power"},
  "switch_1": {"id": "Saklar 1", "en": "Switch 1"},
  "switch_2": {"id": "Saklar 2", "en": "Switch 2"},
  "switch_3": {"id": "Saklar 3", "en": "Switch 3"},
  "switch_4": {"id": "Saklar 4", "en": "Switch 4"},
  "switch_5": {"id": "Saklar 5", "en": "Switch 5"},
  "switch_6": {"id": "Saklar 6", "en": "Switch 6"},
  "switch_alarm_sound": {"id": "Bunyi peringatan", "en": "Alert sound"},
  "switch_antilock_limit": {"id": "Batas kunci ganda", "en": "Double lock limit"},
  "switch_backlight": {"id": "Lampu latar", "en": "Backlight"},
  "switch_charge": {"id": "Kembali mengisi daya", "en": "Return to charge"},
  "switch_disturb": {"id": "Jangan ganggu", "en": "Do not disturb"},
  "switch_enabled": {"id": "Aktifkan sensor", "en": "Sensor enabled"},
  "switch_health_read": {"id": "Mode baca sehat", "en": "Healthy reading"},
  "switch_horizontal": {"id": "Ayun kiri-kanan", "en": "Horizontal swing"},
  "switch_led": {"id": "Lampu nyala/mati", "en": "Light on/off"},
  "switch_led_1": {"id": "Lampu 1", "en": "Light 1"},
  "switch_led_2": {"id": "Lampu 2", "en": "Light 2"},
  "switch_led_3": {"id": "Lampu 3", "en": "Light 3"},
  "switch_microwave": {"id": "Saklar gelombang mikro", "en": "Microwave switch"},
  "switch_sound": {"id": "Suara notifikasi", "en": "Voice prompts"},
  "switch_spray": {"id": "Semprot uap", "en": "Spray"},
  "switch_usb1": {"id": "USB 1", "en": "USB 1"},
  "switch_usb2": {"id": "USB 2", "en": "USB 2"},
  "switch_usb3": {"id": "USB 3", "en": "USB 3"},
  "switch_usb4": {"id": "USB 4", "en": "USB 4"},
  "switch_usb5": {"id": "USB 5", "en": "USB 5"},
  "switch_usb6": {"id": "USB 6", "en": "USB 6"},
  "switch_vertical": {"id": "Ayun atas-bawah", "en": "Vertical swing"},
  "temp": {"id": "Suhu", "en": "Temperature"},
  "temp_alarm": {"id": "Peringatan suhu", "en": "Temperature alert", "pilihan": {"loweralarm": {"id": "Terlalu rendah", "en": "Too low"}, "upperalarm": {"id": "Terlalu tinggi", "en": "Too high"}, "cancel": {"id": "Normal kembali", "en": "Cleared"}}, "bacaSaja": true},
  "temp_boiling_c": {"id": "Suhu setelah mendidih", "en": "After-boil temperature"},
  "temp_boiling_f": {"id": "Suhu setelah didih (°F)", "en": "After-boil temperature (°F)"},
  "temp_boiling_quick_c": {"id": "Didihkan lalu ke", "en": "Boil-then preset", "ketId": "Didihkan dulu, lalu dinginkan ke suhu ini.", "ketEn": "Boil first, then cool to this temperature.", "pilihan": {"50": {"id": "50°C", "en": "50°C"}, "65": {"id": "65°C", "en": "65°C"}, "85": {"id": "85°C", "en": "85°C"}, "90": {"id": "90°C", "en": "90°C"}, "100": {"id": "100°C", "en": "100°C"}}},
  "temp_boiling_quick_f": {"id": "Didihkan lalu ke (°F)", "en": "Boil-then preset (°F)", "pilihan": {"122": {"id": "122°F", "en": "122°F"}, "149": {"id": "149°F", "en": "149°F"}, "185": {"id": "185°F", "en": "185°F"}, "194": {"id": "194°F", "en": "194°F"}, "212": {"id": "212°F", "en": "212°F"}}},
  "temp_correction": {"id": "Koreksi suhu", "en": "Temperature calibration"},
  "temp_current": {"id": "Suhu saat ini", "en": "Current temperature", "bacaSaja": true},
  "temp_current_f": {"id": "Suhu saat ini (°F)", "en": "Current temperature (°F)", "bacaSaja": true},
  "temp_hum_battery_percentage": {"id": "Baterai sensor suhu", "en": "Temp/humidity sensor battery", "bacaSaja": true},
  "temp_indoor": {"id": "Suhu ruangan", "en": "Indoor temperature", "bacaSaja": true},
  "temp_periodic_report": {"id": "Laporan suhu berkala", "en": "Temperature report interval"},
  "temp_sampling": {"id": "Jeda baca suhu", "en": "Temperature sampling"},
  "temp_sensitivity": {"id": "Kepekaan suhu", "en": "Temperature sensitivity"},
  "temp_set": {"id": "Target suhu", "en": "Target temperature"},
  "temp_set_f": {"id": "Target suhu (°F)", "en": "Target temperature (°F)"},
  "temp_setting_quick_c": {"id": "Panaskan cepat ke", "en": "Heat-to preset", "pilihan": {"50": {"id": "50°C", "en": "50°C"}, "65": {"id": "65°C", "en": "65°C"}, "85": {"id": "85°C", "en": "85°C"}, "90": {"id": "90°C", "en": "90°C"}}},
  "temp_setting_quick_f": {"id": "Panaskan cepat ke (°F)", "en": "Heat-to preset (°F)", "pilihan": {"122": {"id": "122°F", "en": "122°F"}, "149": {"id": "149°F", "en": "149°F"}, "185": {"id": "185°F", "en": "185°F"}, "194": {"id": "194°F", "en": "194°F"}, "212": {"id": "212°F", "en": "212°F"}}},
  "temp_unit_convert": {"id": "Satuan suhu", "en": "Temperature unit", "pilihan": {"c": {"id": "Celsius", "en": "Celsius"}, "f": {"id": "Fahrenheit", "en": "Fahrenheit"}}},
  "temp_value": {"id": "Suhu warna", "en": "Color temperature", "ketId": "Putih hangat ke putih dingin.", "ketEn": "Warm to cool white."},
  "temp_value_v2": {"id": "Suhu warna", "en": "Color temperature"},
  "temper_alarm": {"id": "Alarm dibongkar", "en": "Tamper alarm", "ketId": "Menyala jika casing perangkat dibuka/dicopot.", "ketEn": "Triggers when the device casing is opened/removed.", "bacaSaja": true},
  "test_alarm": {"id": "Tes bunyi", "en": "Sound test"},
  "time_total": {"id": "Lama buka-tutup", "en": "Full travel time", "bacaSaja": true},
  "timer": {"id": "Jadwal", "en": "Timer"},
  "total_clean_area": {"id": "Total luas dibersihkan", "en": "Total cleaned area", "bacaSaja": true},
  "total_clean_count": {"id": "Total kali bersih", "en": "Total cleanings", "bacaSaja": true},
  "total_clean_time": {"id": "Total waktu bersih", "en": "Total cleaning time", "bacaSaja": true},
  "total_pm": {"id": "Total partikel tersaring", "en": "Total particles filtered", "bacaSaja": true},
  "total_time": {"id": "Total jam kerja", "en": "Total run time", "bacaSaja": true},
  "tr_timecon": {"id": "Waktu tempuh pintu", "en": "Door travel time"},
  "tvoc": {"id": "Kadar TVOC", "en": "TVOC", "bacaSaja": true},
  "unit": {"id": "Satuan takaran", "en": "Portion unit", "pilihan": {"cup": {"id": "Cangkir", "en": "Cup"}, "oz": {"id": "Ons (oz)", "en": "Ounce"}, "grid": {"id": "Porsi", "en": "Grid"}}},
  "unlock_access_control": {"id": "Dibuka sistem akses", "en": "Unlocked by access control", "bacaSaja": true},
  "unlock_admin": {"id": "Dibuka oleh admin", "en": "Unlocked by admin", "bacaSaja": true},
  "unlock_app": {"id": "Dibuka dari aplikasi", "en": "Unlocked from app", "bacaSaja": true},
  "unlock_ble": {"id": "Dibuka via Bluetooth", "en": "Unlocked via Bluetooth", "bacaSaja": true},
  "unlock_card": {"id": "Dibuka dengan kartu", "en": "Unlocked by card", "bacaSaja": true},
  "unlock_card_kit": {"id": "Riwayat buka kartu", "en": "Card unlock history", "bacaSaja": true},
  "unlock_double": {"id": "Dibuka kombinasi", "en": "Combination unlock", "pilihan": {"password_face": {"id": "Sandi + wajah", "en": "Password + face"}, "finger_password": {"id": "Sidik jari + sandi", "en": "Fingerprint + password"}, "password_card": {"id": "Sandi + kartu", "en": "Password + card"}, "single_unlock": {"id": "Satu cara", "en": "Single method"}, "finger_face": {"id": "Sidik jari + wajah", "en": "Fingerprint + face"}, "finger_card": {"id": "Sidik jari + kartu", "en": "Fingerprint + card"}}, "bacaSaja": true},
  "unlock_double_kit": {"id": "Riwayat buka kombinasi", "en": "Combination unlock history", "bacaSaja": true},
  "unlock_dynamic": {"id": "Dibuka sandi dinamis", "en": "Unlocked by dynamic password", "bacaSaja": true},
  "unlock_emergency": {"id": "Dibuka sandi darurat", "en": "Unlocked by emergency code", "bacaSaja": true},
  "unlock_eye": {"id": "Dibuka dengan iris", "en": "Unlocked by iris", "bacaSaja": true},
  "unlock_face": {"id": "Dibuka dengan wajah", "en": "Unlocked by face", "bacaSaja": true},
  "unlock_face_kit": {"id": "Riwayat buka wajah", "en": "Face unlock history", "bacaSaja": true},
  "unlock_finger_vein": {"id": "Dibuka urat jari", "en": "Unlocked by finger vein", "bacaSaja": true},
  "unlock_fingerprint": {"id": "Dibuka sidik jari", "en": "Unlocked by fingerprint", "bacaSaja": true},
  "unlock_fingerprint_kit": {"id": "Riwayat buka sidik jari", "en": "Fingerprint unlock history", "bacaSaja": true},
  "unlock_hand": {"id": "Dibuka telapak tangan", "en": "Unlocked by palm", "bacaSaja": true},
  "unlock_identity_card": {"id": "Dibuka kartu identitas", "en": "Unlocked by ID card", "bacaSaja": true},
  "unlock_key": {"id": "Dibuka dengan kunci", "en": "Unlocked by key", "bacaSaja": true},
  "unlock_password": {"id": "Dibuka dengan sandi", "en": "Unlocked by password", "bacaSaja": true},
  "unlock_password_kit": {"id": "Riwayat buka sandi", "en": "Password unlock history", "bacaSaja": true},
  "unlock_phone_remote": {"id": "Dibuka dari HP", "en": "Unlocked from phone", "bacaSaja": true},
  "unlock_phone_remote_kit": {"id": "Riwayat buka dari HP", "en": "Phone unlock history", "bacaSaja": true},
  "unlock_remote": {"id": "Dibuka jarak jauh", "en": "Remote unlock", "bacaSaja": true},
  "unlock_special": {"id": "Dibuka kunci khusus", "en": "Unlocked by special key", "bacaSaja": true},
  "unlock_subadmin": {"id": "Dibuka oleh pengelola", "en": "Unlocked by sub-admin", "bacaSaja": true},
  "unlock_switch": {"id": "Cara membuka", "en": "Unlock method", "ketId": "Satu cara atau kombinasi dua cara.", "ketEn": "Single method or a two-method combination.", "pilihan": {"combination": {"id": "Kombinasi", "en": "Combination"}, "single_unlock": {"id": "Satu cara", "en": "Single method"}, "finger_password": {"id": "Sidik jari + sandi", "en": "Fingerprint + password"}, "finger_card": {"id": "Sidik jari + kartu", "en": "Fingerprint + card"}, "finger_face": {"id": "Sidik jari + wajah", "en": "Fingerprint + face"}, "password_card": {"id": "Sandi + kartu", "en": "Password + card"}, "password_face": {"id": "Sandi + wajah", "en": "Password + face"}, "card_face": {"id": "Kartu + wajah", "en": "Card + face"}}},
  "unlock_telecontrol_kit": {"id": "Riwayat buka remote", "en": "Remote control unlock history", "bacaSaja": true},
  "unlock_temporary": {"id": "Dibuka sandi sementara", "en": "Unlocked by temp password", "bacaSaja": true},
  "unlock_temporary_kit": {"id": "Riwayat sandi sementara", "en": "Temp password history", "bacaSaja": true},
  "unlock_voice_remote": {"id": "Dibuka lewat suara", "en": "Unlocked by voice", "bacaSaja": true},
  "upper_temp": {"id": "Suhu maksimum", "en": "Max temperature"},
  "upper_temp_f": {"id": "Suhu maksimum (°F)", "en": "Max temperature (°F)"},
  "use_time": {"id": "Total waktu pakai", "en": "Total usage time"},
  "use_time_one": {"id": "Lama pakai terakhir", "en": "Last usage duration", "bacaSaja": true},
  "uv": {"id": "Sterilisasi UV", "en": "UV sterilization"},
  "va_battery": {"id": "Baterai (lama)", "en": "Battery (legacy)", "bacaSaja": true},
  "va_humidity": {"id": "Kelembapan", "en": "Humidity", "bacaSaja": true},
  "va_temperature": {"id": "Suhu", "en": "Temperature", "bacaSaja": true},
  "valve_check": {"id": "Cek katup", "en": "Valve check"},
  "valve_state": {"id": "Status katup", "en": "Valve status", "pilihan": {"open": {"id": "Terbuka", "en": "Open"}, "close": {"id": "Tertutup", "en": "Closed"}}, "bacaSaja": true},
  "voc_value": {"id": "Kadar VOC", "en": "VOC level", "bacaSaja": true},
  "voice_data": {"id": "Data paket suara", "en": "Voice pack data"},
  "voice_switch": {"id": "Suara robot", "en": "Voice prompts"},
  "voice_times": {"id": "Jumlah panggilan suara", "en": "Voice prompt count"},
  "volume_set": {"id": "Volume", "en": "Volume"},
  "wake_up": {"id": "Bangunkan", "en": "Wake up"},
  "wakeup_mode": {"id": "Mode bangun", "en": "Wake-up (lighting)"},
  "warm": {"id": "Jaga hangat", "en": "Keep warm"},
  "warm_time": {"id": "Lama jaga hangat", "en": "Keep-warm time"},
  "water_once": {"id": "Air sekali siram", "en": "Water per session", "bacaSaja": true},
  "water_set": {"id": "Volume air", "en": "Water volume"},
  "water_total": {"id": "Total pemakaian air", "en": "Total water usage", "bacaSaja": true},
  "watersensor_state": {"id": "Kebocoran air", "en": "Water leak", "pilihan": {"alarm": {"id": "Ada air (bahaya)", "en": "Water detected"}, "normal": {"id": "Normal", "en": "Normal"}}, "bacaSaja": true},
  "weather_delay": {"id": "Tunda karena cuaca", "en": "Weather delay", "pilihan": {"cancel": {"id": "Batal", "en": "Cancel"}, "24h": {"id": "24 jam", "en": "24 h"}, "48h": {"id": "48 jam", "en": "48 h"}, "72h": {"id": "72 jam", "en": "72 h"}}},
  "weather_switch": {"id": "Siram pintar cuaca", "en": "Smart weather"},
  "weight": {"id": "Berat sisa makanan", "en": "Food weight left", "bacaSaja": true},
  "weight_calibrate": {"id": "Kalibrasi sisa makanan", "en": "Calibrate food level"},
  "welcome_words": {"id": "Pesan sambutan", "en": "Welcome message"},
  "wet": {"id": "Pelembap", "en": "Humidification"},
  "window_check": {"id": "Deteksi jendela terbuka", "en": "Open-window detection"},
  "window_state": {"id": "Status jendela", "en": "Window status", "pilihan": {"close": {"id": "Tertutup", "en": "Closed"}, "open": {"id": "Terbuka", "en": "Open"}}, "bacaSaja": true},
  "windshake": {"id": "Ayun", "en": "Swing", "pilihan": {"horizontal": {"id": "Kiri-kanan", "en": "Horizontal"}, "vertical": {"id": "Atas-bawah", "en": "Vertical"}}},
  "windspeed": {"id": "Kecepatan angin", "en": "Fan speed level", "pilihan": {"1": {"id": "Tingkat 1", "en": "Level 1"}, "2": {"id": "Tingkat 2", "en": "Level 2"}, "3": {"id": "Tingkat 3", "en": "Level 3"}, "4": {"id": "Tingkat 4", "en": "Level 4"}, "5": {"id": "Tingkat 5", "en": "Level 5"}, "6": {"id": "Tingkat 6", "en": "Level 6"}}},
  "windspeed_avg": {"id": "Kecepatan angin", "en": "Wind speed"},
  "wireless_awake": {"id": "Status terjaga", "en": "Awake status"},
  "wireless_batterylock": {"id": "Kunci baterai", "en": "Battery lock"},
  "wireless_electricity": {"id": "Baterai", "en": "Battery", "bacaSaja": true},
  "wireless_powermode": {"id": "Sumber daya", "en": "Power source", "pilihan": {"0": {"id": "Baterai", "en": "Battery"}, "1": {"id": "Listrik / mengisi daya", "en": "Mains / charging"}}, "bacaSaja": true},
  "work_days": {"id": "Hari kerja", "en": "Work days", "pilihan": {"5_2": {"id": "5 hari kerja + 2 libur", "en": "5+2 days"}, "6_1": {"id": "6 hari kerja + 1 libur", "en": "6+1 days"}, "7": {"id": "7 hari", "en": "7 days"}}},
  "work_life_1": {"id": "Umur batang magnesium", "en": "Magnesium rod life", "bacaSaja": true},
  "work_life_2": {"id": "Umur tangki", "en": "Tank liner life", "bacaSaja": true},
  "work_mode": {"id": "Mode lampu", "en": "Light mode", "pilihan": {"white": {"id": "Putih", "en": "White"}, "colour": {"id": "Warna", "en": "Colour"}, "colourful": {"id": "Warna-warni", "en": "Colourful"}, "colourful1": {"id": "Warna-warni", "en": "Colourful"}, "scene": {"id": "Adegan", "en": "Scene"}, "music": {"id": "Musik", "en": "Music"}, "scene_1": {"id": "Adegan 1", "en": "Scene 1"}, "scene_2": {"id": "Adegan 2", "en": "Scene 2"}, "scene_3": {"id": "Adegan 3", "en": "Scene 3"}, "scene_4": {"id": "Adegan 4", "en": "Scene 4"}, "light_white": {"id": "Putih", "en": "White"}}},
  "work_power": {"id": "Daya aktual", "en": "Actual power", "bacaSaja": true},
  "work_state": {"id": "Status kerja", "en": "Working status", "pilihan": {"heating": {"id": "Memanaskan", "en": "Heating"}, "warming": {"id": "Menghangatkan", "en": "Warming"}, "cold": {"id": "Dingin", "en": "Cool"}, "hot": {"id": "Panas", "en": "Heat"}, "wind": {"id": "Kipas", "en": "Fan"}, "comfortable": {"id": "Nyaman", "en": "Comfort"}, "energy": {"id": "Hemat energi", "en": "Energy saving"}, "auto": {"id": "Otomatis", "en": "Auto"}, "holiday": {"id": "Liburan", "en": "Holiday"}, "eco": {"id": "Hemat", "en": "Eco"}, "manual": {"id": "Manual", "en": "Manual"}, "sleep": {"id": "Tidur", "en": "Sleep"}, "dry": {"id": "Kering", "en": "Dry"}, "program": {"id": "Terjadwal", "en": "Program"}, "floor_heat": {"id": "Pemanas lantai", "en": "Floor heating"}, "auxiliary_heat": {"id": "Pemanas tambahan", "en": "Auxiliary heat"}, "opening": {"id": "Membuka", "en": "Opening"}, "closing": {"id": "Menutup", "en": "Closing"}, "warm": {"id": "Jaga hangat", "en": "Keeping warm"}, "idle": {"id": "Diam", "en": "Idle"}}, "bacaSaja": true},
  "work_status": {"id": "Status kerja", "en": "Working status", "pilihan": {"heating": {"id": "Memanaskan", "en": "Heating"}, "cooling": {"id": "Mendinginkan", "en": "Cooling"}, "ventilation": {"id": "Ventilasi", "en": "Ventilation"}, "off": {"id": "Mati", "en": "Off"}}, "bacaSaja": true},
  "work_type": {"id": "Jenis kerja", "en": "Work type", "pilihan": {"setting_quick": {"id": "Panaskan cepat", "en": "Quick heat"}, "boiling_quick": {"id": "Didihkan cepat", "en": "Quick boil"}, "temp_setting": {"id": "Panaskan ke suhu", "en": "Heat to temp"}, "temp_boiling": {"id": "Didihkan lalu ke suhu", "en": "Boil then to temp"}}},
  "zoom_control": {"id": "Zoom", "en": "Zoom", "pilihan": {"0": {"id": "Perkecil (zoom out)", "en": "Zoom out"}, "1": {"id": "Perbesar (zoom in)", "en": "Zoom in"}}},
  "zoom_stop": {"id": "Hentikan zoom", "en": "Stop zoom"},
};
