// Dibuat scripts/kamus-pc.ts dari src/lib/i18n/kamus. Jangan diubah tangan.
window.KAMUS = {
  "id": {
    "merek": {
      "nama": "AntiKebo"
    },
    "umum": {
      "lanjut": "Lanjut",
      "kembali": "Kembali",
      "batal": "Batal",
      "simpan": "Simpan",
      "tutup": "Tutup",
      "selesai": "Selesai",
      "cobaLagi": "Coba lagi",
      "memuat": "Memuat...",
      "menyimpan": "Menyimpan...",
      "galatUmum": "Ada yang tidak beres. Coba lagi sebentar.",
      "tersalin": "Tersalin",
      "lanjutan": "Lanjutan",
      "terputus": "Koneksi terputus. Menyambung ulang...",
      "kurangi": "Kurangi",
      "tambah": "Tambah",
      "kamu": "kamu"
    },
    "pc": {
      "judul": "AntiKebo untuk PC",
      "sambung": "Sambungkan PC ini",
      "sambungKet": "Sambungkan sekali. Sesudah itu alarm berbunyi di PC ini walau browser ditutup.",
      "kodeJudul": "Kode sambung",
      "kodeKet": "Browser sudah terbuka. Masuk ke AntiKebo, pastikan kodenya sama, lalu tekan Sambungkan.",
      "bukaLagi": "Buka halaman sambung lagi",
      "menunggu": "Menunggu persetujuan...",
      "kodeHabis": "Kodenya kedaluwarsa. Minta kode baru ya.",
      "gagalKode": "Belum bisa terhubung ke AntiKebo. Periksa internet, lalu coba lagi.",
      "tersambung": "Tersambung ke {nama}",
      "alarmBerikut": "Alarm berikutnya {jam}",
      "tanpaAlarm": "Belum ada alarm 24 jam ke depan",
      "periksa": "Daftar periksa",
      "server": "Tersambung ke AntiKebo",
      "serverPutus": "Koneksi putus. Jadwal tetap dipegang PC ini.",
      "mulaiWindows": "Menyala saat Windows hidup",
      "nyalakan": "Nyalakan",
      "tidakTidur": "Tidak tidur saat ada alarm",
      "tutupLaptop": "Tetap bangun saat laptop ditutup sambil dicas",
      "perbaiki": "Perbaiki",
      "tutupGagal": "Belum bisa diubah otomatis. Coba lagi, lalu izinkan bila Windows bertanya.",
      "suaraAda": "Speaker atau headset siap",
      "suaraTidakAda": "Tidak ada speaker. Pasang speaker atau headset.",
      "dicas": "PC sedang dicas",
      "belumDicas": "PC belum dicas. Colokkan charger sebelum tidur.",
      "tesBunyi": "Tes bunyi",
      "dengar": "Kamu dengar?",
      "ya": "Ya",
      "tidak": "Tidak",
      "dengarYa": "Mantap, bunyinya sampai.",
      "dengarTidak": "Periksa speaker dan volume, lalu tes lagi. Saat alarm, volume dinaikkan otomatis.",
      "versi": "Versi {v}",
      "putuskan": "Putuskan PC ini",
      "keluar": "Keluar dari AntiKebo",
      "terkunci": "Mode Komitmen aktif. Keluar dibuka lagi sesudah alarm selesai.",
      "terkunciBerbunyi": "Alarm sedang berbunyi. Jawab soalnya dulu.",
      "baki": {
        "buka": "Buka AntiKebo",
        "tes": "Tes bunyi",
        "keluar": "Keluar",
        "siaga": "Siaga untuk {jam}",
        "tanpaAlarm": "Tidak ada alarm 24 jam ke depan",
        "belum": "Belum tersambung",
        "putus": "Koneksi putus, jadwal tetap dipegang"
      },
      "notif": {
        "belumDicasJudul": "PC belum dicas",
        "belumDicasIsi": "Colokkan charger supaya alarm {jam} tetap berbunyi.",
        "tersambungJudul": "PC tersambung",
        "tersambungIsi": "Alarm akan berbunyi di PC ini.",
        "terkunciJudul": "Belum bisa keluar"
      },
      "alarm": {
        "memuat": "Mengambil soal...",
        "putus": "Koneksi putus. Jawab soal dari PC ini untuk mematikan alarm.",
        "luringJudul": "Soal dari PC ini",
        "luringTerkirim": "Jawabanmu dikirim begitu internet kembali.",
        "qrPc": "Kode QR dipindai lewat HP. Di PC, ganti dengan soal hitungan.",
        "gantiHitungan": "Ganti soal hitungan",
        "selesaiLain": "Soalnya sudah dijawab di perangkat lain.",
        "ditunda": "Ditunda. Alarm berbunyi lagi {jam}.",
        "tutup": "Tutup",
        "lihatUtama": "Lihat layar utama"
      }
    },
    "bunyi": {
      "salah": "Salah, soal baru ya",
      "benar": "Benar! Satu lagi",
      "beruntun": "Benar berturut-turut",
      "tunda": "Tunda {menit} menit (sisa {sisa})",
      "tundaHabis": "Jatah tunda habis",
      "urutan": "{ke} dari {dari}",
      "jawaban": "Jawaban",
      "hapus": "Hapus angka",
      "kirim": "Kirim jawaban",
      "omelan": "Omelan yang sedang diputar",
      "qrJudul": "Pindai kode di kamar mandi",
      "qrKet": "Arahkan kamera ke kode QR {tempat}.",
      "qrGanti": "Kamera bermasalah? Ganti soal hitungan",
      "terlambat": "Terlambat {n} menit karena gangguan",
      "ingatLihat": "Ingat angka ini",
      "ingatKetik": "Ketik angka tadi",
      "ketikJudul": "Ketik kalimat ini persis",
      "ketikPlaceholder": "Ketik di sini",
      "atau": "atau",
      "tempatBawaan": "tempat yang kamu pilih",
      "qrJudulTempat": "Pindai kode di {tempat}",
      "qrArahkan": "Arahkan kamera ke kode QR yang kamu tempel.",
      "qrSalah": "Bukan kode yang ini. Pindai kode yang benar.",
      "kameraDitolak": "Kamera tidak bisa dibuka. Izinkan kamera, atau ganti soal hitungan.",
      "tahap": "Langkah {ke} dari {dari}",
      "tahapQr": "Bagus! Sekarang pindai kodenya.",
      "diganti": "Diganti soal hitungan berat, 3 kali benar.",
      "soalTunda": "Soal tunda",
      "kembaliSoal": "Kembali ke soal",
      "ditundaJudul": "Tidur sebentar",
      "ditundaIsi": "{judul} berbunyi lagi saat hitungan ini habis.",
      "ditundaSisa": "Sisa tunda {n}",
      "belumBerbunyi": "Alarm ini belum berbunyi.",
      "tidakBangun": "Alarm berhenti sendiri karena batas waktunya habis.",
      "sudahSelesai": "Alarm ini sudah selesai.",
      "keBeranda": "Ke beranda"
    },
    "pagi": {
      "judul": "Selamat pagi, {nama}!",
      "bangun": "Kamu bangun {jam}",
      "agendaHariIni": "Agenda hari ini",
      "skor": "Skor bangun",
      "tunda": "Tunda",
      "lama": "Sampai bangun",
      "menit": "{n} mnt",
      "cekLagi": "Aku cek lagi {n} menit lagi ya.",
      "oke": "Oke",
      "uji": "Uji"
    },
    "cek": {
      "judul": "Masih bangun?",
      "tombol": "Masih!",
      "sisa": "{n} detik",
      "ket": "Kalau tidak diketuk, alarm bunyi lagi."
    }
  },
  "en": {
    "merek": {
      "nama": "AntiKebo"
    },
    "umum": {
      "lanjut": "Continue",
      "kembali": "Back",
      "batal": "Cancel",
      "simpan": "Save",
      "tutup": "Close",
      "selesai": "Done",
      "cobaLagi": "Try again",
      "memuat": "Loading...",
      "menyimpan": "Saving...",
      "galatUmum": "Something went wrong. Try again in a moment.",
      "tersalin": "Copied",
      "lanjutan": "Advanced",
      "terputus": "Connection lost. Reconnecting...",
      "kurangi": "Decrease",
      "tambah": "Increase",
      "kamu": "you"
    },
    "pc": {
      "judul": "AntiKebo for PC",
      "sambung": "Connect this PC",
      "sambungKet": "Connect once. After that, alarms ring on this PC even with the browser closed.",
      "kodeJudul": "Connection code",
      "kodeKet": "Your browser is open. Sign in to AntiKebo, check that the code matches, then press Connect.",
      "bukaLagi": "Open the connect page again",
      "menunggu": "Waiting for approval...",
      "kodeHabis": "The code expired. Get a new one.",
      "gagalKode": "Can't reach AntiKebo yet. Check your internet, then try again.",
      "tersambung": "Connected to {nama}",
      "alarmBerikut": "Next alarm {jam}",
      "tanpaAlarm": "No alarms in the next 24 hours",
      "periksa": "Checklist",
      "server": "Connected to AntiKebo",
      "serverPutus": "Offline. This PC still keeps the schedule.",
      "mulaiWindows": "Starts with Windows",
      "nyalakan": "Turn on",
      "tidakTidur": "Won't sleep before an alarm",
      "tutupLaptop": "Stays awake when the lid is closed while charging",
      "perbaiki": "Fix",
      "tutupGagal": "Couldn't change it automatically. Try again and allow it if Windows asks.",
      "suaraAda": "Speaker or headset ready",
      "suaraTidakAda": "No speaker found. Plug in a speaker or headset.",
      "dicas": "PC is charging",
      "belumDicas": "PC isn't charging. Plug in the charger before bed.",
      "tesBunyi": "Test sound",
      "dengar": "Can you hear it?",
      "ya": "Yes",
      "tidak": "No",
      "dengarYa": "Great, the sound comes through.",
      "dengarTidak": "Check the speaker and volume, then test again. During an alarm the volume goes up automatically.",
      "versi": "Version {v}",
      "putuskan": "Disconnect this PC",
      "keluar": "Quit AntiKebo",
      "terkunci": "Commitment Mode is on. You can quit again after the alarm is done.",
      "terkunciBerbunyi": "The alarm is ringing. Solve the challenge first.",
      "baki": {
        "buka": "Open AntiKebo",
        "tes": "Test sound",
        "keluar": "Quit",
        "siaga": "Standing by for {jam}",
        "tanpaAlarm": "No alarms in the next 24 hours",
        "belum": "Not connected",
        "putus": "Offline, schedule kept on this PC"
      },
      "notif": {
        "belumDicasJudul": "PC isn't charging",
        "belumDicasIsi": "Plug in the charger so the {jam} alarm still rings.",
        "tersambungJudul": "PC connected",
        "tersambungIsi": "Alarms will ring on this PC.",
        "terkunciJudul": "Can't quit yet"
      },
      "alarm": {
        "memuat": "Getting your challenge...",
        "putus": "Offline. Solve the challenge from this PC to stop the alarm.",
        "luringJudul": "Challenge from this PC",
        "luringTerkirim": "Your answers are sent as soon as the internet is back.",
        "qrPc": "QR codes are scanned with your phone. On a PC, switch to a math challenge.",
        "gantiHitungan": "Switch to math",
        "selesaiLain": "The challenge was solved on another device.",
        "ditunda": "Snoozed. The alarm rings again at {jam}.",
        "tutup": "Close",
        "lihatUtama": "Look at the main screen"
      }
    },
    "bunyi": {
      "salah": "Wrong, here's a new one",
      "benar": "Correct! One more",
      "beruntun": "Correct in a row",
      "tunda": "Snooze {menit} min ({sisa} left)",
      "tundaHabis": "No snoozes left",
      "urutan": "{ke} of {dari}",
      "jawaban": "Answer",
      "hapus": "Delete digit",
      "kirim": "Submit answer",
      "omelan": "Scolding now playing",
      "qrJudul": "Scan the code in your bathroom",
      "qrKet": "Point the camera at the QR code {tempat}.",
      "qrGanti": "Camera trouble? Switch to math",
      "terlambat": "{n} minutes late due to a disruption",
      "ingatLihat": "Remember this number",
      "ingatKetik": "Type the number",
      "ketikJudul": "Type this sentence exactly",
      "ketikPlaceholder": "Type here",
      "atau": "or",
      "tempatBawaan": "the place you chose",
      "qrJudulTempat": "Scan the code in {tempat}",
      "qrArahkan": "Point the camera at the QR code you stuck up.",
      "qrSalah": "Not this code. Scan the right one.",
      "kameraDitolak": "The camera won't open. Allow the camera, or switch to math.",
      "tahap": "Step {ke} of {dari}",
      "tahapQr": "Nice! Now scan the code.",
      "diganti": "Switched to hard math, 3 correct.",
      "soalTunda": "Snooze challenge",
      "kembaliSoal": "Back to the challenge",
      "ditundaJudul": "A short nap",
      "ditundaIsi": "{judul} rings again when this countdown ends.",
      "ditundaSisa": "Snoozes left: {n}",
      "belumBerbunyi": "This alarm hasn't rung yet.",
      "tidakBangun": "The alarm stopped by itself because its time limit ran out.",
      "sudahSelesai": "This alarm is already over.",
      "keBeranda": "Go home"
    },
    "pagi": {
      "judul": "Good morning, {nama}!",
      "bangun": "You woke up at {jam}",
      "agendaHariIni": "Today's agenda",
      "skor": "Wake score",
      "tunda": "Snoozes",
      "lama": "Time to wake",
      "menit": "{n} min",
      "cekLagi": "I'll check on you again in {n} minutes.",
      "oke": "OK",
      "uji": "Test"
    },
    "cek": {
      "judul": "Still awake?",
      "tombol": "Yes!",
      "sisa": "{n} seconds",
      "ket": "If you don't tap, the alarm rings again."
    }
  }
};
