; Terjemahan Bahasa Indonesia pesan pemasang Tauri (NSIS bawaan Tauri tidak punya). Kunci sama
; dengan English.nsh milik tauri-bundler; tanpa tanda pisah panjang.
LangString addOrReinstall ${LANG_INDONESIAN} "Tambah atau pasang ulang komponen"
LangString alreadyInstalled ${LANG_INDONESIAN} "Sudah terpasang"
LangString alreadyInstalledLong ${LANG_INDONESIAN} "${PRODUCTNAME} ${VERSION} sudah terpasang. Pilih tindakan yang diinginkan, lalu lanjutkan."
LangString appRunning ${LANG_INDONESIAN} "${PRODUCTNAME} sedang berjalan. Tutup dulu, lalu coba lagi."
LangString appRunningOkKill ${LANG_INDONESIAN} "${PRODUCTNAME} sedang berjalan.$\nKlik OK untuk menutupnya."
LangString chooseMaintenanceOption ${LANG_INDONESIAN} "Pilih pemeliharaan yang ingin dilakukan."
LangString choowHowToInstall ${LANG_INDONESIAN} "Pilih cara memasang ${PRODUCTNAME}."
LangString createDesktop ${LANG_INDONESIAN} "Buat pintasan di desktop"
LangString dontUninstall ${LANG_INDONESIAN} "Jangan copot"
LangString dontUninstallDowngrade ${LANG_INDONESIAN} "Jangan copot (pemasang ini tidak mengizinkan turun versi tanpa mencopot)"
LangString failedToKillApp ${LANG_INDONESIAN} "Gagal menutup ${PRODUCTNAME}. Tutup dulu, lalu coba lagi."
LangString installingWebview2 ${LANG_INDONESIAN} "Memasang WebView2..."
LangString newerVersionInstalled ${LANG_INDONESIAN} "Versi ${PRODUCTNAME} yang lebih baru sudah terpasang. Memasang versi lama tidak disarankan; kalau tetap ingin, copot dulu versi yang sekarang. Pilih tindakan yang diinginkan, lalu lanjutkan."
LangString older ${LANG_INDONESIAN} "lebih lama"
LangString olderOrUnknownVersionInstalled ${LANG_INDONESIAN} "Versi ${PRODUCTNAME} yang $R4 sudah terpasang. Sebaiknya copot dulu sebelum memasang. Pilih tindakan yang diinginkan, lalu lanjutkan."
LangString silentDowngrades ${LANG_INDONESIAN} "Pemasang ini tidak mengizinkan turun versi, jadi pemasangan diam tidak bisa dilanjutkan. Pakai pemasang biasa.$\n"
LangString unableToUninstall ${LANG_INDONESIAN} "Tidak bisa mencopot!"
LangString uninstallApp ${LANG_INDONESIAN} "Copot ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_INDONESIAN} "Copot sebelum memasang"
LangString unknown ${LANG_INDONESIAN} "tidak dikenal"
LangString webview2AbortError ${LANG_INDONESIAN} "Gagal memasang WebView2. Aplikasi tidak bisa jalan tanpanya. Coba jalankan pemasang lagi."
LangString webview2DownloadError ${LANG_INDONESIAN} "Gagal mengunduh WebView2: $0"
LangString webview2DownloadSuccess ${LANG_INDONESIAN} "Pemasang WebView2 berhasil diunduh"
LangString webview2Downloading ${LANG_INDONESIAN} "Mengunduh pemasang WebView2..."
LangString webview2InstallError ${LANG_INDONESIAN} "Gagal memasang WebView2, kode keluar $1"
LangString webview2InstallSuccess ${LANG_INDONESIAN} "WebView2 berhasil dipasang"
LangString deleteAppData ${LANG_INDONESIAN} "Hapus data aplikasi"
